ANTLR3C: src/antlr3commontoken.c File Reference
antlr3commontoken.c File Reference
#include <antlr3.h>
Functions
ANTLR3_API pANTLR3_COMMON_TOKEN antlr3CommonTokenNew (ANTLR3_UINT32 ttype)
ANTLR3_API void antlr3SetTokenAPI (pANTLR3_COMMON_TOKEN token)
ANTLR3_API pANTLR3_TOKEN_FACTORY antlr3TokenFactoryNew (pANTLR3_INPUT_STREAM input)
static void factoryClose (pANTLR3_TOKEN_FACTORY factory)
static void factoryReset (pANTLR3_TOKEN_FACTORY factory)
static ANTLR3_UINT32 getChannel (pANTLR3_COMMON_TOKEN token)
static ANTLR3_INT32 getCharPositionInLine (pANTLR3_COMMON_TOKEN token)
static ANTLR3_UINT32 getLine (pANTLR3_COMMON_TOKEN token)
static ANTLR3_MARKER getStartIndex (pANTLR3_COMMON_TOKEN token)
static ANTLR3_MARKER getStopIndex (pANTLR3_COMMON_TOKEN token)
static pANTLR3_STRING getText (pANTLR3_COMMON_TOKEN token)
Contains the default implementation of the common token used within java.
static ANTLR3_MARKER getTokenIndex (pANTLR3_COMMON_TOKEN token)
static ANTLR3_UINT32 getType (pANTLR3_COMMON_TOKEN token)
static void newPool (pANTLR3_TOKEN_FACTORY factory)
static pANTLR3_COMMON_TOKEN newPoolToken (pANTLR3_TOKEN_FACTORY factory)
static pANTLR3_COMMON_TOKEN newToken (void)
static void setChannel (pANTLR3_COMMON_TOKEN token, ANTLR3_UINT32 channel)
static void setCharPositionInLine (pANTLR3_COMMON_TOKEN token, ANTLR3_INT32 pos)
static void setInputStream (pANTLR3_TOKEN_FACTORY factory, pANTLR3_INPUT_STREAM input)
static void setLine (pANTLR3_COMMON_TOKEN token, ANTLR3_UINT32 line)
static void setStartIndex (pANTLR3_COMMON_TOKEN token, ANTLR3_MARKER index)
static void setStopIndex (pANTLR3_COMMON_TOKEN token, ANTLR3_MARKER index)
static void setText (pANTLR3_COMMON_TOKEN token, pANTLR3_STRING text)
Install the supplied text string as teh text for the token.
static void setText8 (pANTLR3_COMMON_TOKEN token, pANTLR3_UINT8 text)
static void setTokenIndex (pANTLR3_COMMON_TOKEN token, ANTLR3_MARKER)
static void setType (pANTLR3_COMMON_TOKEN token, ANTLR3_UINT32 type)
static pANTLR3_STRING toString (pANTLR3_COMMON_TOKEN token)
Function Documentation
ANTLR3_API pANTLR3_COMMON_TOKEN antlr3CommonTokenNew (ANTLR3_UINT32 ttype)
References newToken(), and ANTLR3_COMMON_TOKEN_struct::setType.
Referenced by antlr3CommonTreeNodeStreamNew().
ANTLR3_API void antlr3SetTokenAPI (pANTLR3_COMMON_TOKEN token)
References getChannel(), ANTLR3_COMMON_TOKEN_struct::getChannel, getCharPositionInLine(), ANTLR3_COMMON_TOKEN_struct::getCharPositionInLine, getLine(), ANTLR3_COMMON_TOKEN_struct::getLine, getStartIndex(), ANTLR3_COMMON_TOKEN_struct::getStartIndex, getStopIndex(), ANTLR3_COMMON_TOKEN_struct::getStopIndex, getText(), ANTLR3_COMMON_TOKEN_struct::getText, getTokenIndex(), ANTLR3_COMMON_TOKEN_struct::getTokenIndex, getType(), ANTLR3_COMMON_TOKEN_struct::getType, setChannel(), ANTLR3_COMMON_TOKEN_struct::setChannel, setCharPositionInLine(), ANTLR3_COMMON_TOKEN_struct::setCharPositionInLine, setLine(), ANTLR3_COMMON_TOKEN_struct::setLine, setStartIndex(), ANTLR3_COMMON_TOKEN_struct::setStartIndex, setStopIndex(), ANTLR3_COMMON_TOKEN_struct::setStopIndex, setText(), ANTLR3_COMMON_TOKEN_struct::setText, setText8(), ANTLR3_COMMON_TOKEN_struct::setText8, setTokenIndex(), ANTLR3_COMMON_TOKEN_struct::setTokenIndex, setType(), ANTLR3_COMMON_TOKEN_struct::setType, toString(), and ANTLR3_COMMON_TOKEN_struct::toString.
Referenced by antlr3LexerNew(), antlr3TokenFactoryNew(), newPoolToken(), and newToken().
ANTLR3_API pANTLR3_TOKEN_FACTORY antlr3TokenFactoryNew (pANTLR3_INPUT_STREAM input)
References ANTLR3_MALLOC, ANTLR3_TRUE, antlr3SetTokenAPI(), ANTLR3_TOKEN_FACTORY_struct::close, factoryClose(), ANTLR3_COMMON_TOKEN_struct::factoryMade, factoryReset(), ANTLR3_TOKEN_FACTORY_struct::maxPool, newPool(), newPoolToken(), ANTLR3_TOKEN_FACTORY_struct::newToken, ANTLR3_TOKEN_FACTORY_struct::pools, ANTLR3_TOKEN_FACTORY_struct::reset, setInputStream(), ANTLR3_TOKEN_FACTORY_struct::setInputStream, ANTLR3_TOKEN_FACTORY_struct::thisPool, and ANTLR3_TOKEN_FACTORY_struct::unTruc.
Referenced by ANTLR3_TREE_ADAPTORNew(), getMissingSymbol(), and setCharStream().
static void factoryClose (pANTLR3_TOKEN_FACTORY factory) [static]
References ANTLR3_FACTORY_POOL_SIZE, ANTLR3_FREE, ANTLR3_COMMON_TOKEN_struct::custom, ANTLR3_COMMON_TOKEN_struct::freeCustom, ANTLR3_TOKEN_FACTORY_struct::nextToken, ANTLR3_TOKEN_FACTORY_struct::pools, and ANTLR3_TOKEN_FACTORY_struct::thisPool.
Referenced by antlr3ArboretumNew(), and antlr3TokenFactoryNew().
static void factoryReset (pANTLR3_TOKEN_FACTORY factory) [static]
References newPool(), and ANTLR3_TOKEN_FACTORY_struct::thisPool.
Referenced by antlr3TokenFactoryNew().
static ANTLR3_UINT32 getChannel (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_COMMON_TOKEN_struct::channel.
Referenced by antlr3SetTokenAPI().
static ANTLR3_INT32 getCharPositionInLine (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_COMMON_TOKEN_struct::charPosition.
static ANTLR3_UINT32 getLine (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_COMMON_TOKEN_struct::line.
static ANTLR3_MARKER getStartIndex (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_INPUT_STREAM_struct::data, ANTLR3_COMMON_TOKEN_struct::input, and ANTLR3_COMMON_TOKEN_struct::start.
Referenced by antlr3SetTokenAPI().
static ANTLR3_MARKER getStopIndex (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_COMMON_TOKEN_struct::stop.
Referenced by antlr3SetTokenAPI().
static pANTLR3_STRING getText (pANTLR3_COMMON_TOKEN token) [static]
Contains the default implementation of the common token used within java.
Custom tokens should create this structure and then append to it using the custom pointer to install their own structure and API.
References ANTLR3_TEXT_CHARP, ANTLR3_TEXT_STRING, ANTLR3_TOKEN_EOF, ANTLR3_COMMON_TOKEN_struct::chars, ANTLR3_COMMON_TOKEN_struct::getStartIndex, ANTLR3_COMMON_TOKEN_struct::getStopIndex, ANTLR3_COMMON_TOKEN_struct::input, ANTLR3_STRING_FACTORY_struct::newStr8, ANTLR3_COMMON_TOKEN_struct::strFactory, ANTLR3_INPUT_STREAM_struct::substr, ANTLR3_COMMON_TOKEN_struct::text, ANTLR3_COMMON_TOKEN_struct::textState, ANTLR3_COMMON_TOKEN_struct::tokText, and ANTLR3_COMMON_TOKEN_struct::type.
static ANTLR3_MARKER getTokenIndex (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_COMMON_TOKEN_struct::index.
Referenced by antlr3SetTokenAPI().
static ANTLR3_UINT32 getType (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_COMMON_TOKEN_struct::type.
static void newPool (pANTLR3_TOKEN_FACTORY factory) [static]
References ANTLR3_CALLOC, ANTLR3_FACTORY_POOL_SIZE, ANTLR3_REALLOC, ANTLR3_TOKEN_FACTORY_struct::maxPool, ANTLR3_TOKEN_FACTORY_struct::nextToken, ANTLR3_TOKEN_FACTORY_struct::pools, and ANTLR3_TOKEN_FACTORY_struct::thisPool.
static pANTLR3_COMMON_TOKEN newPoolToken (pANTLR3_TOKEN_FACTORY factory) [static]
References ANTLR3_FACTORY_POOL_SIZE, ANTLR3_TRUE, antlr3SetTokenAPI(), ANTLR3_COMMON_TOKEN_struct::factoryMade, ANTLR3_COMMON_TOKEN_struct::input, ANTLR3_TOKEN_FACTORY_struct::input, newPool(), ANTLR3_TOKEN_FACTORY_struct::nextToken, ANTLR3_TOKEN_FACTORY_struct::pools, ANTLR3_COMMON_TOKEN_struct::setStartIndex, ANTLR3_INPUT_STREAM_struct::strFactory, ANTLR3_COMMON_TOKEN_struct::strFactory, and ANTLR3_TOKEN_FACTORY_struct::thisPool.
Referenced by antlr3TokenFactoryNew().
static pANTLR3_COMMON_TOKEN newToken (void) [static]
References ANTLR3_CALLOC, ANTLR3_FALSE, antlr3SetTokenAPI(), and ANTLR3_COMMON_TOKEN_struct::factoryMade.
Referenced by antlr3CommonTokenNew(), createToken(), and createTokenFromToken().
static void setChannel (pANTLR3_COMMON_TOKEN token, ANTLR3_UINT32 channel) [static]
References ANTLR3_COMMON_TOKEN_struct::channel.
Referenced by antlr3SetTokenAPI().
static void setCharPositionInLine (pANTLR3_COMMON_TOKEN token, ANTLR3_INT32 pos) [static]
References ANTLR3_COMMON_TOKEN_struct::charPosition.
Referenced by antlr3SetTokenAPI().
static void setInputStream (pANTLR3_TOKEN_FACTORY factory, pANTLR3_INPUT_STREAM input) [static]
References ANTLR3_COMMON_TOKEN_struct::input, ANTLR3_TOKEN_FACTORY_struct::input, ANTLR3_INPUT_STREAM_struct::strFactory, ANTLR3_COMMON_TOKEN_struct::strFactory, and ANTLR3_TOKEN_FACTORY_struct::unTruc.
Referenced by antlr3TokenFactoryNew().
static void setLine (pANTLR3_COMMON_TOKEN token, ANTLR3_UINT32 line) [static]
References ANTLR3_COMMON_TOKEN_struct::line.
Referenced by antlr3SetTokenAPI().
static void setStartIndex (pANTLR3_COMMON_TOKEN token, ANTLR3_MARKER index) [static]
References ANTLR3_COMMON_TOKEN_struct::start.
Referenced by antlr3SetTokenAPI().
static void setStopIndex (pANTLR3_COMMON_TOKEN token, ANTLR3_MARKER index) [static]
References ANTLR3_COMMON_TOKEN_struct::stop.
Referenced by antlr3SetTokenAPI().
static void setText (pANTLR3_COMMON_TOKEN token, pANTLR3_STRING text) [static]
Install the supplied text string as teh text for the token.
The method assumes that the existing text (if any) was created by a factory and so does not attempt to release any memory it is using.Text not created by a string fctory (not advised) should be released prior to this call.
References ANTLR3_TEXT_STRING, ANTLR3_COMMON_TOKEN_struct::text, ANTLR3_COMMON_TOKEN_struct::textState, and ANTLR3_COMMON_TOKEN_struct::tokText.
static void setText8 (pANTLR3_COMMON_TOKEN token, pANTLR3_UINT8 text) [static]
References ANTLR3_TEXT_CHARP, ANTLR3_TEXT_NONE, ANTLR3_COMMON_TOKEN_struct::chars, ANTLR3_STRING_struct::set8, ANTLR3_COMMON_TOKEN_struct::text, ANTLR3_COMMON_TOKEN_struct::textState, and ANTLR3_COMMON_TOKEN_struct::tokText.
static void setTokenIndex (pANTLR3_COMMON_TOKEN token, ANTLR3_MARKER index) [static]
References ANTLR3_COMMON_TOKEN_struct::index.
Referenced by antlr3SetTokenAPI().
static void setType (pANTLR3_COMMON_TOKEN token, ANTLR3_UINT32 type) [static]
References ANTLR3_COMMON_TOKEN_struct::type.
static pANTLR3_STRING toString (pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_STRING_struct::addc, ANTLR3_STRING_struct::addi, ANTLR3_TOKEN_DEFAULT_CHANNEL, ANTLR3_STRING_struct::append8, ANTLR3_STRING_struct::appendS, ANTLR3_STRING_struct::factory, ANTLR3_COMMON_TOKEN_struct::getChannel, ANTLR3_COMMON_TOKEN_struct::getCharPositionInLine, ANTLR3_COMMON_TOKEN_struct::getLine, ANTLR3_COMMON_TOKEN_struct::getStartIndex, ANTLR3_COMMON_TOKEN_struct::getStopIndex, ANTLR3_COMMON_TOKEN_struct::getText, ANTLR3_COMMON_TOKEN_struct::getTokenIndex, ANTLR3_STRING_FACTORY_struct::newRaw, and ANTLR3_COMMON_TOKEN_struct::type.
Referenced by antlr3CommonTokenStreamNew(), antlr3CommonTreeNodeStreamNew(), antlr3CommonTreeNodeStreamNewStream(), antlr3SetCTAPI(), and antlr3SetTokenAPI().