ANTLR3C: src/antlr3parser.c File Reference
antlr3parser.c File Reference
Detailed Description
Implementation of the base functionality for an ANTLR3 parser.
#include <antlr3parser.h>
Functions
ANTLR3_API pANTLR3_PARSER antlr3ParserNew (ANTLR3_UINT32 sizeHint, pANTLR3_RECOGNIZER_SHARED_STATE state)
ANTLR3_API pANTLR3_PARSER antlr3ParserNewStream (ANTLR3_UINT32 sizeHint, pANTLR3_TOKEN_STREAM tstream, pANTLR3_RECOGNIZER_SHARED_STATE state)
ANTLR3_API pANTLR3_PARSER antlr3ParserNewStreamDbg (ANTLR3_UINT32 sizeHint, pANTLR3_TOKEN_STREAM tstream, pANTLR3_DEBUG_EVENT_LISTENER dbg, pANTLR3_RECOGNIZER_SHARED_STATE state)
static void freeParser (pANTLR3_PARSER parser)
static pANTLR3_TOKEN_STREAM getTokenStream (pANTLR3_PARSER parser)
static void setDebugListener (pANTLR3_PARSER parser, pANTLR3_DEBUG_EVENT_LISTENER dbg)
static void setTokenStream (pANTLR3_PARSER parser, pANTLR3_TOKEN_STREAM)
Function Documentation
ANTLR3_API pANTLR3_PARSER antlr3ParserNew (ANTLR3_UINT32 sizeHint, pANTLR3_RECOGNIZER_SHARED_STATE state)
References ANTLR3_MALLOC, ANTLR3_TYPE_PARSER, antlr3BaseRecognizerNew(), antlr3MTExceptionNew(), ANTLR3_BASE_RECOGNIZER_struct::exConstruct, ANTLR3_PARSER_struct::free, freeParser(), getTokenStream(), ANTLR3_PARSER_struct::getTokenStream, ANTLR3_PARSER_struct::rec, setDebugListener(), ANTLR3_PARSER_struct::setDebugListener, setTokenStream(), ANTLR3_PARSER_struct::setTokenStream, and ANTLR3_BASE_RECOGNIZER_struct::super.
Referenced by antlr3ParserNewStream().
ANTLR3_API pANTLR3_PARSER antlr3ParserNewStream (ANTLR3_UINT32 sizeHint, pANTLR3_TOKEN_STREAM tstream, pANTLR3_RECOGNIZER_SHARED_STATE state)
References antlr3ParserNew(), and ANTLR3_PARSER_struct::setTokenStream.
Referenced by antlr3ParserNewStreamDbg().
ANTLR3_API pANTLR3_PARSER antlr3ParserNewStreamDbg (ANTLR3_UINT32 sizeHint, pANTLR3_TOKEN_STREAM tstream, pANTLR3_DEBUG_EVENT_LISTENER dbg, pANTLR3_RECOGNIZER_SHARED_STATE state)
References antlr3ParserNewStream(), and ANTLR3_PARSER_struct::setDebugListener.
static void freeParser (pANTLR3_PARSER parser) [static]
References ANTLR3_FREE, ANTLR3_RECOGNIZER_SHARED_STATE_struct::following, ANTLR3_BASE_RECOGNIZER_struct::free, ANTLR3_STACK_struct::free, ANTLR3_PARSER_struct::rec, and ANTLR3_BASE_RECOGNIZER_struct::state.
Referenced by antlr3ParserNew(), and antlr3TreeParserNewStream().
static pANTLR3_TOKEN_STREAM getTokenStream (pANTLR3_PARSER parser) [static]
References ANTLR3_PARSER_struct::tstream.
Referenced by antlr3ParserNew().
static void setDebugListener (pANTLR3_PARSER parser, pANTLR3_DEBUG_EVENT_LISTENER dbg) [static]
References ANTLR3_BASE_RECOGNIZER_struct::debugger, ANTLR3_PARSER_struct::rec, ANTLR3_TOKEN_STREAM_struct::setDebugListener, and ANTLR3_PARSER_struct::tstream.
Referenced by antlr3CommonTokenStreamNew(), and antlr3ParserNew().
static void setTokenStream (pANTLR3_PARSER parser, pANTLR3_TOKEN_STREAM tstream) [static]
References ANTLR3_PARSER_struct::rec, ANTLR3_BASE_RECOGNIZER_struct::reset, and ANTLR3_PARSER_struct::tstream.
Referenced by antlr3ParserNew().