ANTLR3C: src/antlr3commontree.c File Reference
antlr3commontree.c File Reference
#include <antlr3commontree.h>
Functions
ANTLR3_API pANTLR3_ARBORETUM antlr3ArboretumNew (pANTLR3_STRING_FACTORY strFactory)
ANTLR3_API pANTLR3_COMMON_TREE antlr3CommonTreeNew ()
ANTLR3_API pANTLR3_COMMON_TREE antlr3CommonTreeNewFromToken (pANTLR3_COMMON_TOKEN token)
ANTLR3_API void antlr3SetCTAPI (pANTLR3_COMMON_TREE tree)
static void createChildrenList (pANTLR3_BASE_TREE tree)
Create a new vector for holding child nodes using the inbuilt vector factory.
static pANTLR3_BASE_TREE dupNode (pANTLR3_BASE_TREE tree)
static void factoryClose (pANTLR3_ARBORETUM factory)
static ANTLR3_UINT32 getCharPositionInLine (pANTLR3_BASE_TREE tree)
static ANTLR3_INT32 getChildIndex (pANTLR3_BASE_TREE tree)
static ANTLR3_UINT32 getLine (pANTLR3_BASE_TREE tree)
static pANTLR3_BASE_TREE getParent (pANTLR3_BASE_TREE tree)
static pANTLR3_STRING getText (pANTLR3_BASE_TREE tree)
static pANTLR3_COMMON_TOKEN getToken (pANTLR3_BASE_TREE tree)
static ANTLR3_UINT32 getType (pANTLR3_BASE_TREE tree)
static ANTLR3_BOOLEAN isNilNode (pANTLR3_BASE_TREE tree)
static pANTLR3_BASE_TREE newFromToken (pANTLR3_ARBORETUM factory, pANTLR3_COMMON_TOKEN token)
static pANTLR3_BASE_TREE newFromTree (pANTLR3_ARBORETUM factory, pANTLR3_COMMON_TREE tree)
static void newPool (pANTLR3_ARBORETUM factory)
static pANTLR3_BASE_TREE newPoolTree (pANTLR3_ARBORETUM factory)
static void reuse (pANTLR3_BASE_TREE tree)
Clean up any child vector that the tree might have, so it can be reused, then add it into the reuse stack.
static void setChildIndex (pANTLR3_BASE_TREE tree, ANTLR3_INT32 i)
static void setParent (pANTLR3_BASE_TREE tree, pANTLR3_BASE_TREE parent)
static pANTLR3_STRING toString (pANTLR3_BASE_TREE tree)
Function Documentation
ANTLR3_API pANTLR3_ARBORETUM antlr3ArboretumNew (pANTLR3_STRING_FACTORY strFactory)
References ANTLR3_MALLOC, antlr3SetCTAPI(), antlr3StackNew(), antlr3VectorFactoryNew(), ANTLR3_COMMON_TREE_struct::baseTree, ANTLR3_ARBORETUM_struct::close, ANTLR3_COMMON_TREE_struct::factory, factoryClose(), ANTLR3_TREE_PARSER_struct::free, newFromToken(), ANTLR3_ARBORETUM_struct::newFromToken, newFromTree(), ANTLR3_ARBORETUM_struct::newFromTree, newPool(), newPoolTree(), ANTLR3_ARBORETUM_struct::newTree, ANTLR3_ARBORETUM_struct::nilStack, ANTLR3_ARBORETUM_struct::pools, ANTLR3_BASE_TREE_struct::strFactory, ANTLR3_ARBORETUM_struct::thisPool, ANTLR3_ARBORETUM_struct::unTruc, and ANTLR3_ARBORETUM_struct::vFactory.
Referenced by ANTLR3_TREE_ADAPTORNew().
ANTLR3_API pANTLR3_COMMON_TREE antlr3CommonTreeNew (void)
References ANTLR3_MALLOC, and antlr3SetCTAPI().
Referenced by antlr3CommonTreeNewFromToken().
ANTLR3_API pANTLR3_COMMON_TREE antlr3CommonTreeNewFromToken (pANTLR3_COMMON_TOKEN token)
References antlr3CommonTreeNew(), and ANTLR3_COMMON_TREE_struct::token.
ANTLR3_API void antlr3SetCTAPI (pANTLR3_COMMON_TREE tree)
References antlr3BaseTreeNew(), ANTLR3_COMMON_TREE_struct::baseTree, ANTLR3_COMMON_TREE_struct::childIndex, ANTLR3_BASE_TREE_struct::children, createChildrenList(), ANTLR3_BASE_TREE_struct::createChildrenList, dupNode(), ANTLR3_BASE_TREE_struct::dupNode, ANTLR3_BASE_TREE_struct::free, getCharPositionInLine(), ANTLR3_BASE_TREE_struct::getCharPositionInLine, getChildIndex(), ANTLR3_BASE_TREE_struct::getChildIndex, getLine(), ANTLR3_BASE_TREE_struct::getLine, getParent(), ANTLR3_BASE_TREE_struct::getParent, getText(), ANTLR3_BASE_TREE_struct::getText, getToken(), ANTLR3_BASE_TREE_struct::getToken, getType(), ANTLR3_BASE_TREE_struct::getType, isNilNode(), ANTLR3_BASE_TREE_struct::isNilNode, ANTLR3_COMMON_TREE_struct::parent, reuse(), ANTLR3_BASE_TREE_struct::reuse, setChildIndex(), ANTLR3_BASE_TREE_struct::setChildIndex, setParent(), ANTLR3_BASE_TREE_struct::setParent, ANTLR3_COMMON_TREE_struct::startIndex, ANTLR3_COMMON_TREE_struct::stopIndex, ANTLR3_BASE_TREE_struct::super, ANTLR3_COMMON_TREE_struct::token, toString(), ANTLR3_BASE_TREE_struct::toString, and ANTLR3_BASE_TREE_struct::u.
Referenced by antlr3ArboretumNew(), antlr3CommonTreeNew(), antlr3CommonTreeNodeStreamNew(), antlr3CommonTreeNodeStreamNewStream(), and newPoolTree().
static void createChildrenList (pANTLR3_BASE_TREE tree) [static]
Create a new vector for holding child nodes using the inbuilt vector factory.
References ANTLR3_BASE_TREE_struct::children, and ANTLR3_BASE_TREE_struct::super.
Referenced by antlr3SetCTAPI().
static pANTLR3_BASE_TREE dupNode (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_COMMON_TREE_struct::factory, ANTLR3_ARBORETUM_struct::newFromTree, and ANTLR3_BASE_TREE_struct::super.
Referenced by ANTLR3_TREE_ADAPTORNew(), and antlr3SetCTAPI().
static void factoryClose (pANTLR3_ARBORETUM factory) [static]
References ANTLR3_FREE, ANTLR3_VECTOR_FACTORY_struct::close, ANTLR3_STACK_struct::free, ANTLR3_ARBORETUM_struct::nilStack, ANTLR3_ARBORETUM_struct::pools, ANTLR3_ARBORETUM_struct::thisPool, and ANTLR3_ARBORETUM_struct::vFactory.
static ANTLR3_UINT32 getCharPositionInLine (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_BASE_TREE_struct::getCharPositionInLine, ANTLR3_COMMON_TOKEN_struct::getCharPositionInLine, ANTLR3_BASE_TREE_struct::getChild, ANTLR3_BASE_TREE_struct::getChildCount, and ANTLR3_BASE_TREE_struct::super.
static ANTLR3_INT32 getChildIndex (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_BASE_TREE_struct::super.
Referenced by ANTLR3_TREE_ADAPTORNew(), and antlr3SetCTAPI().
static ANTLR3_UINT32 getLine (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_BASE_TREE_struct::getChild, ANTLR3_BASE_TREE_struct::getChildCount, ANTLR3_BASE_TREE_struct::getLine, ANTLR3_COMMON_TOKEN_struct::getLine, ANTLR3_BASE_TREE_struct::super, and ANTLR3_COMMON_TREE_struct::token.
static pANTLR3_BASE_TREE getParent (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_BASE_TREE_struct::super.
Referenced by ANTLR3_TREE_ADAPTORNew(), and antlr3SetCTAPI().
static pANTLR3_STRING getText (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_BASE_TREE_struct::toString.
static pANTLR3_COMMON_TOKEN getToken (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_BASE_TREE_struct::super.
Referenced by antlr3SetCTAPI().
static ANTLR3_UINT32 getType (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_COMMON_TOKEN_struct::getType, ANTLR3_BASE_TREE_struct::super, and ANTLR3_COMMON_TREE_struct::token.
static ANTLR3_BOOLEAN isNilNode (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_FALSE, ANTLR3_TRUE, and ANTLR3_BASE_TREE_struct::super.
static pANTLR3_BASE_TREE newFromToken (pANTLR3_ARBORETUM factory, pANTLR3_COMMON_TOKEN token) [static]
References ANTLR3_ARBORETUM_struct::newTree, and ANTLR3_BASE_TREE_struct::super.
Referenced by antlr3ArboretumNew().
static pANTLR3_BASE_TREE newFromTree (pANTLR3_ARBORETUM factory, pANTLR3_COMMON_TREE tree) [static]
References ANTLR3_COMMON_TREE_struct::baseTree, ANTLR3_ARBORETUM_struct::newTree, ANTLR3_BASE_TREE_struct::super, ANTLR3_COMMON_TREE_struct::token, and ANTLR3_BASE_TREE_struct::u.
Referenced by antlr3ArboretumNew().
static void newPool (pANTLR3_ARBORETUM factory) [static]
References ANTLR3_FACTORY_POOL_SIZE, ANTLR3_MALLOC, ANTLR3_REALLOC, ANTLR3_ARBORETUM_struct::nextTree, ANTLR3_ARBORETUM_struct::pools, and ANTLR3_ARBORETUM_struct::thisPool.
static pANTLR3_BASE_TREE newPoolTree (pANTLR3_ARBORETUM factory) [static]
References ANTLR3_FACTORY_POOL_SIZE, antlr3SetCTAPI(), ANTLR3_COMMON_TREE_struct::baseTree, ANTLR3_COMMON_TREE_struct::factory, newPool(), ANTLR3_ARBORETUM_struct::nextTree, ANTLR3_ARBORETUM_struct::nilStack, ANTLR3_STACK_struct::peek, ANTLR3_ARBORETUM_struct::pools, ANTLR3_STACK_struct::pop, ANTLR3_BASE_TREE_struct::strFactory, ANTLR3_BASE_TREE_struct::super, ANTLR3_ARBORETUM_struct::thisPool, and ANTLR3_ARBORETUM_struct::unTruc.
Referenced by antlr3ArboretumNew().
static void reuse (pANTLR3_BASE_TREE tree) [static]
Clean up any child vector that the tree might have, so it can be reused, then add it into the reuse stack.
References ANTLR3_COMMON_TREE_struct::baseTree, ANTLR3_BASE_TREE_struct::children, ANTLR3_VECTOR_struct::clear, ANTLR3_COMMON_TREE_struct::factory, ANTLR3_ARBORETUM_struct::nilStack, ANTLR3_STACK_struct::push, and ANTLR3_BASE_TREE_struct::super.
Referenced by antlr3SetCTAPI().
static void setChildIndex (pANTLR3_BASE_TREE tree, ANTLR3_INT32 i) [static]
References ANTLR3_BASE_TREE_struct::super.
Referenced by ANTLR3_TREE_ADAPTORNew(), and antlr3SetCTAPI().
static void setParent (pANTLR3_BASE_TREE tree, pANTLR3_BASE_TREE parent) [static]
References ANTLR3_BASE_TREE_struct::super.
Referenced by ANTLR3_TREE_ADAPTORNew(), and antlr3SetCTAPI().
static pANTLR3_STRING toString (pANTLR3_BASE_TREE tree) [static]
References ANTLR3_TRUE, ANTLR3_BASE_TREE_struct::isNilNode, ANTLR3_STRING_FACTORY_struct::newPtr, nilNode(), ANTLR3_BASE_TREE_struct::strFactory, and ANTLR3_BASE_TREE_struct::super.