ANTLR3C: PANTLR3_INT_STREAM
PANTLR3_INT_STREAM
Functions
ANTLR3_API pANTLR3_INT_STREAM antlr3IntStreamNew ()
static void freeStream (pANTLR3_INT_STREAM stream)
Function Documentation
ANTLR3_API pANTLR3_INT_STREAM antlr3IntStreamNew (void)
References ANTLR3_CALLOC, ANTLR3_INT_STREAM_struct::free, and freeStream().
Referenced by antlr3CommonTokenStreamNew(), antlr3CommonTreeNodeStreamNew(), antlr3CommonTreeNodeStreamNewStream(), and antlr3GenericSetupStream().
static void freeStream (pANTLR3_INT_STREAM stream) [static]
References ANTLR3_FREE.
Referenced by antlr3IntStreamNew().