ANTLR3C: ANTLR3_BASE_TREE_ADAPTOR_struct Struct Reference
ANTLR3_BASE_TREE_ADAPTOR_struct Struct Reference
#include <antlr3basetreeadaptor.h>
Data Fields
void(* addChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, void *child)
void(* addChildToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, pANTLR3_COMMON_TOKEN child)
void *(* becomeRoot)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *newRoot, void *oldRoot)
void *(* becomeRootToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *newRoot, void *oldRoot)
void *(* create)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_COMMON_TOKEN payload)
pANTLR3_COMMON_TOKEN(* createToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_UINT8 text)
pANTLR3_COMMON_TOKEN(* createTokenFromToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_COMMON_TOKEN fromToken)
void *(* createTypeText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_UINT8 text)
void *(* createTypeToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_COMMON_TOKEN fromToken)
void *(* createTypeTokenText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_COMMON_TOKEN fromToken, pANTLR3_UINT8 text)
pANTLR3_DEBUG_EVENT_LISTENER debugger
If set to something other than NULL, then this structure is points to an instance of the debugger interface.
void(* deleteChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i)
void *(* dupNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *treeNode)
void *(* dupTree)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *tree)
void *(* dupTreeTT)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, void *tree)
void *(* errorNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_TOKEN_STREAM tnstream, pANTLR3_COMMON_TOKEN startToken, pANTLR3_COMMON_TOKEN stopToken, pANTLR3_EXCEPTION e)
void(* free)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor)
void *(* getChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i)
ANTLR3_UINT32(* getChildCount)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *)
ANTLR3_INT32(* getChildIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
void *(* getParent)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *child)
pANTLR3_STRING(* getText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
pANTLR3_COMMON_TOKEN(* getToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
ANTLR3_MARKER(* getTokenStartIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
ANTLR3_MARKER(* getTokenStopIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
ANTLR3_UINT32(* getType)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
ANTLR3_UINT32(* getUniqueID)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *)
ANTLR3_BOOLEAN(* isNilNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
pANTLR3_STRING(* makeDot)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *theTree)
Produce a DOT (see graphviz freeware suite) from a base tree.
void *(* nilNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor)
void(* replaceChildren)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *parent, ANTLR3_INT32 startChildIndex, ANTLR3_INT32 stopChildIndex, void *t)
Replace from start to stop child index of parent with t, which might be a list.
void *(* rulePostProcessing)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *root)
void(* setChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i, void *child)
void(* setChildIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i)
void(* setDebugEventListener)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_DEBUG_EVENT_LISTENER debugger)
void(* setParent)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *child, void *parent)
void(* setText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_STRING t)
void(* setText8)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_UINT8 t)
void(* setTokenBoundaries)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, pANTLR3_COMMON_TOKEN startToken, pANTLR3_COMMON_TOKEN stopToken)
void(* setType)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 type)
pANTLR3_STRING_FACTORY strFactory
We need a string factory for creating imaginary tokens, we take this from the stream we are supplied to walk.
void * super
Pointer to any enclosing structure/interface that contains this structure.
pANTLR3_TOKEN_FACTORY tokenFactory
Field Documentation
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::addChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, void *child)
Referenced by addChildToken(), antlr3BaseTreeAdaptorInit(), dbgAddChildToken(), and dupTreeTT().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::addChildToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, pANTLR3_COMMON_TOKEN child)
Referenced by antlr3BaseTreeAdaptorInit().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::becomeRoot)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *newRoot, void *oldRoot)
Referenced by antlr3BaseTreeAdaptorInit(), becomeRootToken(), and dbgBecomeRootToken().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::becomeRootToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *newRoot, void *oldRoot)
Referenced by antlr3BaseTreeAdaptorInit().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::create)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_COMMON_TOKEN payload)
Referenced by addChildToken(), ANTLR3_TREE_ADAPTORDebugNew(), ANTLR3_TREE_ADAPTORNew(), becomeRootToken(), createTypeText(), createTypeToken(), createTypeTokenText(), dbgAddChildToken(), dbgBecomeRootToken(), dbgNil(), nextNodeToken(), nilNode(), and setDebugEventListener().
pANTLR3_COMMON_TOKEN(* ANTLR3_BASE_TREE_ADAPTOR_struct::createToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_UINT8 text)
Referenced by ANTLR3_TREE_ADAPTORNew(), and createTypeText().
pANTLR3_COMMON_TOKEN(* ANTLR3_BASE_TREE_ADAPTOR_struct::createTokenFromToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_COMMON_TOKEN fromToken)
Referenced by ANTLR3_TREE_ADAPTORNew(), createTypeToken(), and createTypeTokenText().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::createTypeText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_UINT8 text)
Referenced by antlr3BaseTreeAdaptorInit(), and errorNode().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::createTypeToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_COMMON_TOKEN fromToken)
Referenced by antlr3BaseTreeAdaptorInit().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::createTypeTokenText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, ANTLR3_UINT32 tokenType, pANTLR3_COMMON_TOKEN fromToken, pANTLR3_UINT8 text)
Referenced by antlr3BaseTreeAdaptorInit().
pANTLR3_DEBUG_EVENT_LISTENER ANTLR3_BASE_TREE_ADAPTOR_struct::debugger
If set to something other than NULL, then this structure is points to an instance of the debugger interface.
In general, the debugger is only referenced internally in recovery/error operations so that it does not cause overhead by having to check this pointer in every function/method
Referenced by dbgAddChild(), dbgAddChildToken(), dbgBecomeRoot(), dbgBecomeRootToken(), dbgCreate(), dbgCreateTypeText(), dbgCreateTypeToken(), dbgCreateTypeTokenText(), dbgNil(), dbgSetTokenBoundaries(), and simulateTreeConstruction().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::deleteChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i)
Referenced by ANTLR3_TREE_ADAPTORNew().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::dupNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *treeNode)
Referenced by ANTLR3_TREE_ADAPTORNew(), dupTree(), nextNode(), and toTreeNode().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::dupTree)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *tree)
Referenced by antlr3BaseTreeAdaptorInit().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::dupTreeTT)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, void *tree)
Referenced by antlr3BaseTreeAdaptorInit(), dbgDupTree(), dupTree(), and dupTreeTT().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::errorNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_TOKEN_STREAM tnstream, pANTLR3_COMMON_TOKEN startToken, pANTLR3_COMMON_TOKEN stopToken, pANTLR3_EXCEPTION e)
Referenced by ANTLR3_TREE_ADAPTORNew().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::free)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor)
Referenced by ANTLR3_TREE_ADAPTORNew(), antlr3CommonTreeNodeStreamFree(), and antlr3CommonTreeNodeStreamNew().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::getChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i)
Referenced by ANTLR3_TREE_ADAPTORNew(), antlr3BaseTreeAdaptorInit(), defineDotEdges(), defineDotNodes(), dupTreeTT(), fillBuffer(), and simulateTreeConstruction().
ANTLR3_UINT32(* ANTLR3_BASE_TREE_ADAPTOR_struct::getChildCount)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *)
Referenced by ANTLR3_TREE_ADAPTORNew(), antlr3BaseTreeAdaptorInit(), defineDotEdges(), defineDotNodes(), dupTreeTT(), and simulateTreeConstruction().
ANTLR3_INT32(* ANTLR3_BASE_TREE_ADAPTOR_struct::getChildIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
Referenced by ANTLR3_TREE_ADAPTORNew().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::getParent)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *child)
Referenced by ANTLR3_TREE_ADAPTORNew().
pANTLR3_STRING(* ANTLR3_BASE_TREE_ADAPTOR_struct::getText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
Referenced by ANTLR3_TREE_ADAPTORNew(), antlr3BaseTreeAdaptorInit(), defineDotEdges(), defineDotNodes(), makeDot(), and serializeNode().
pANTLR3_COMMON_TOKEN(* ANTLR3_BASE_TREE_ADAPTOR_struct::getToken)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
Referenced by serializeNode().
ANTLR3_MARKER(* ANTLR3_BASE_TREE_ADAPTOR_struct::getTokenStartIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
Referenced by ANTLR3_TREE_ADAPTORNew(), and serializeNode().
ANTLR3_MARKER(* ANTLR3_BASE_TREE_ADAPTOR_struct::getTokenStopIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
Referenced by ANTLR3_TREE_ADAPTORNew().
ANTLR3_UINT32(* ANTLR3_BASE_TREE_ADAPTOR_struct::getType)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
Referenced by ANTLR3_TREE_ADAPTORNew(), antlr3BaseTreeAdaptorInit(), and serializeNode().
ANTLR3_UINT32(* ANTLR3_BASE_TREE_ADAPTOR_struct::getUniqueID)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *)
Referenced by antlr3BaseTreeAdaptorInit(), and serializeNode().
ANTLR3_BOOLEAN(* ANTLR3_BASE_TREE_ADAPTOR_struct::isNilNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t)
Referenced by antlr3BaseTreeAdaptorInit(), and fillBuffer().
pANTLR3_STRING(* ANTLR3_BASE_TREE_ADAPTOR_struct::makeDot)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *theTree)
Produce a DOT (see graphviz freeware suite) from a base tree.
Referenced by antlr3BaseTreeAdaptorInit().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::nilNode)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor)
Referenced by antlr3BaseTreeAdaptorInit().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::replaceChildren)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *parent, ANTLR3_INT32 startChildIndex, ANTLR3_INT32 stopChildIndex, void *t)
Replace from start to stop child index of parent with t, which might be a list.
Number of children may be different after this call.
If parent is null, don't do anything; must be at root of overall tree. Can't replace whatever points to the parent externally. Do nothing.
Referenced by ANTLR3_TREE_ADAPTORNew().
void*(* ANTLR3_BASE_TREE_ADAPTOR_struct::rulePostProcessing)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *root)
Referenced by antlr3BaseTreeAdaptorInit().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setChild)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i, void *child)
Referenced by ANTLR3_TREE_ADAPTORNew().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setChildIndex)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 i)
Referenced by ANTLR3_TREE_ADAPTORNew(), and dupTreeTT().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setDebugEventListener)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_DEBUG_EVENT_LISTENER debugger)
Referenced by ANTLR3_TREE_ADAPTORNew().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setParent)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *child, void *parent)
Referenced by ANTLR3_TREE_ADAPTORNew(), and dupTreeTT().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setText)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_STRING t)
Referenced by antlr3BaseTreeAdaptorInit().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setText8)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, pANTLR3_UINT8 t)
Referenced by antlr3BaseTreeAdaptorInit().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setTokenBoundaries)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, pANTLR3_COMMON_TOKEN startToken, pANTLR3_COMMON_TOKEN stopToken)
Referenced by ANTLR3_TREE_ADAPTORDebugNew(), ANTLR3_TREE_ADAPTORNew(), and setDebugEventListener().
void(* ANTLR3_BASE_TREE_ADAPTOR_struct::setType)(struct ANTLR3_BASE_TREE_ADAPTOR_struct *adaptor, void *t, ANTLR3_UINT32 type)
Referenced by antlr3BaseTreeAdaptorInit().
pANTLR3_STRING_FACTORY ANTLR3_BASE_TREE_ADAPTOR_struct::strFactory
We need a string factory for creating imaginary tokens, we take this from the stream we are supplied to walk.
Referenced by ANTLR3_TREE_ADAPTORNew(), createToken(), createTokenFromToken(), and makeDot().
void* ANTLR3_BASE_TREE_ADAPTOR_struct::super
Pointer to any enclosing structure/interface that contains this structure.
Referenced by add(), ANTLR3_TREE_ADAPTORNew(), create(), ctaFree(), freeNodeRS(), and freeRS().
pANTLR3_TOKEN_FACTORY ANTLR3_BASE_TREE_ADAPTOR_struct::tokenFactory
Referenced by ANTLR3_TREE_ADAPTORNew(), createToken(), createTokenFromToken(), and ctaFree().
The documentation for this struct was generated from the following file:
include/antlr3basetreeadaptor.h