ANTLR3C: ANTLR3_BITSET_struct Struct Reference
ANTLR3_BITSET_struct Struct Reference
#include <antlr3bitset.h>
Data Fields
void(* add)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_INT32 bit)
ANTLR3_BITSET_LIST blist
The actual bits themselves.
pANTLR3_BITSET(* bor)(struct ANTLR3_BITSET_struct *bitset1, struct ANTLR3_BITSET_struct *bitset2)
void(* borInPlace)(struct ANTLR3_BITSET_struct *bitset, struct ANTLR3_BITSET_struct *bitset2)
pANTLR3_BITSET(* clone)(struct ANTLR3_BITSET_struct *inSet)
ANTLR3_BOOLEAN(* equals)(struct ANTLR3_BITSET_struct *bitset1, struct ANTLR3_BITSET_struct *bitset2)
void(* free)(struct ANTLR3_BITSET_struct *bitset)
void(* grow)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_INT32 newSize)
ANTLR3_BOOLEAN(* isMember)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_UINT32 bit)
ANTLR3_BOOLEAN(* isNilNode)(struct ANTLR3_BITSET_struct *bitset)
ANTLR3_UINT32(* numBits)(struct ANTLR3_BITSET_struct *bitset)
void(* remove)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_UINT32 bit)
ANTLR3_UINT32(* size)(struct ANTLR3_BITSET_struct *bitset)
pANTLR3_INT32(* toIntList)(struct ANTLR3_BITSET_struct *bitset)
Field Documentation
void(* ANTLR3_BITSET_struct::add)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_INT32 bit)
Referenced by addEdge(), antlr3BitsetList(), antlr3BitsetSetAPI(), and DFS().
ANTLR3_BITSET_LIST ANTLR3_BITSET_struct::blist
The actual bits themselves.
Referenced by antlr3BitsetAdd(), antlr3BitsetClone(), antlr3BitsetCopy(), antlr3BitsetEquals(), antlr3BitsetFree(), antlr3BitsetIsNil(), antlr3BitsetLoad(), antlr3BitsetMember(), antlr3BitsetNew(), antlr3BitsetNumBits(), antlr3BitsetORInPlace(), antlr3BitsetRemove(), antlr3BitsetSize(), grow(), and growToInclude().
pANTLR3_BITSET(* ANTLR3_BITSET_struct::bor)(struct ANTLR3_BITSET_struct *bitset1, struct ANTLR3_BITSET_struct *bitset2)
Referenced by antlr3BitsetSetAPI().
void(* ANTLR3_BITSET_struct::borInPlace)(struct ANTLR3_BITSET_struct *bitset, struct ANTLR3_BITSET_struct *bitset2)
Referenced by antlr3BitsetSetAPI(), combineFollows(), and mismatchIsMissingToken().
pANTLR3_BITSET(* ANTLR3_BITSET_struct::clone)(struct ANTLR3_BITSET_struct *inSet)
Referenced by antlr3BitsetSetAPI().
ANTLR3_BOOLEAN(* ANTLR3_BITSET_struct::equals)(struct ANTLR3_BITSET_struct *bitset1, struct ANTLR3_BITSET_struct *bitset2)
Referenced by antlr3BitsetSetAPI().
void(* ANTLR3_BITSET_struct::free)(struct ANTLR3_BITSET_struct *bitset)
Referenced by antlr3BitsetSetAPI(), combineFollows(), freeTopo(), getTokensList(), getTokensType(), mismatchIsMissingToken(), recover(), and recoverFromMismatchedElement().
void(* ANTLR3_BITSET_struct::grow)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_INT32 newSize)
Referenced by antlr3BitsetLoad(), antlr3BitsetSetAPI(), and growToInclude().
ANTLR3_BOOLEAN(* ANTLR3_BITSET_struct::isMember)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_UINT32 bit)
Referenced by antlr3BitsetSetAPI(), antlr3BitsetToIntList(), combineFollows(), DFS(), getTokensSet(), mismatchIsMissingToken(), recoverFromMismatchedElement(), and sortToArray().
ANTLR3_BOOLEAN(* ANTLR3_BITSET_struct::isNilNode)(struct ANTLR3_BITSET_struct *bitset)
Referenced by antlr3BitsetSetAPI().
ANTLR3_UINT32(* ANTLR3_BITSET_struct::numBits)(struct ANTLR3_BITSET_struct *bitset)
Referenced by antlr3BitsetSetAPI(), antlr3BitsetToIntList(), DFS(), and displayRecognitionError().
void(* ANTLR3_BITSET_struct::remove)(struct ANTLR3_BITSET_struct *bitset, ANTLR3_UINT32 bit)
Referenced by antlr3BitsetSetAPI(), combineFollows(), mismatchIsMissingToken(), and recoverFromMismatchedElement().
ANTLR3_UINT32(* ANTLR3_BITSET_struct::size)(struct ANTLR3_BITSET_struct *bitset)
Referenced by antlr3BitsetSetAPI(), antlr3BitsetToIntList(), DFS(), and displayRecognitionError().
pANTLR3_INT32(* ANTLR3_BITSET_struct::toIntList)(struct ANTLR3_BITSET_struct *bitset)
Referenced by antlr3BitsetSetAPI().
The documentation for this struct was generated from the following file:
include/antlr3bitset.h