ANTLR3C: ANTLR3_STACK_struct Struct Reference
ANTLR3_STACK_struct Struct Reference
#include <antlr3collections.h>
Detailed Description
Structure that represents a Stack collection.
Data Fields
void(* free)(struct ANTLR3_STACK_struct *stack)
void *(* get)(struct ANTLR3_STACK_struct *stack, ANTLR3_INTKEY key)
void *(* peek)(struct ANTLR3_STACK_struct *stack)
void *(* pop)(struct ANTLR3_STACK_struct *stack)
ANTLR3_BOOLEAN(* push)(struct ANTLR3_STACK_struct *stack, void *element, void(ANTLR3_CDECL *freeptr)(void *))
ANTLR3_UINT32(* size)(struct ANTLR3_STACK_struct *stack)
void * top
Used for quick access to the top of the stack.
pANTLR3_VECTOR vector
List that supports the stack structure.
Field Documentation
void(* ANTLR3_STACK_struct::free)(struct ANTLR3_STACK_struct *stack)
Referenced by antlr3CommonTreeNodeStreamFree(), antlr3StackNew(), closeVectorFactory(), factoryClose(), freeLexer(), freeParser(), and reset().
void*(* ANTLR3_STACK_struct::get)(struct ANTLR3_STACK_struct *stack, ANTLR3_INTKEY key)
Referenced by antlr3StackNew(), and combineFollows().
void*(* ANTLR3_STACK_struct::peek)(struct ANTLR3_STACK_struct *stack)
Referenced by antlr3StackNew(), newPoolTree(), and newVector().
void*(* ANTLR3_STACK_struct::pop)(struct ANTLR3_STACK_struct *stack)
Referenced by antlr3StackNew(), newPoolTree(), newVector(), and popCharStream().
ANTLR3_BOOLEAN(* ANTLR3_STACK_struct::push)(struct ANTLR3_STACK_struct *stack, void *element, void(ANTLR3_CDECL *freeptr)(void *))
Referenced by antlr3StackNew(), pushCharStream(), returnVector(), and reuse().
ANTLR3_UINT32(* ANTLR3_STACK_struct::size)(struct ANTLR3_STACK_struct *stack)
Referenced by antlr3StackNew(), combineFollows(), nextToken(), and popCharStream().
void* ANTLR3_STACK_struct::top
Used for quick access to the top of the stack.
Referenced by antlr3StackFree(), antlr3StackNew(), antlr3StackPeek(), antlr3StackPop(), antlr3StackPush(), and popCharStream().
pANTLR3_VECTOR ANTLR3_STACK_struct::vector
List that supports the stack structure.
Referenced by antlr3StackFree(), antlr3StackGet(), antlr3StackNew(), antlr3StackPop(), antlr3StackPush(), antlr3StackSize(), and mismatchIsMissingToken().
The documentation for this struct was generated from the following file:
include/antlr3collections.h