ANTLR3C: ANTLR3_STRING_FACTORY_struct Struct Reference
ANTLR3_STRING_FACTORY_struct Struct Reference
#include <antlr3string.h>
Detailed Description
Definition of the string factory interface, which creates and tracks strings for you of various shapes and sizes.
Data Fields
void(* close)(struct ANTLR3_STRING_FACTORY_struct *factory)
Pointer to function that closes the factory.
void(* destroy)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_STRING string)
Pointer to function that deletes the string altogether.
ANTLR3_UINT32 index
pANTLR3_STRING(* newPtr)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string, ANTLR3_UINT32 size)
Pointer to function that manufactures a string from a given pointer and length.
pANTLR3_STRING(* newPtr8)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string, ANTLR3_UINT32 size)
Pointer to function that manufactures a string from a given pointer and length.
pANTLR3_STRING(* newRaw)(struct ANTLR3_STRING_FACTORY_struct *factory)
Pointer to function that manufactures an empty string.
pANTLR3_STRING(* newSize)(struct ANTLR3_STRING_FACTORY_struct *factory, ANTLR3_UINT32 size)
Pointer to function that manufactures a raw string with no text in it but space for size characters.
pANTLR3_STRING(* newStr)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string)
Pointer to function that manufactures a string from a given pointer and works out the length.
pANTLR3_STRING(* newStr8)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string)
Pointer to function that manufactures a string from a given pointer and length.
pANTLR3_STRING(* printable)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_STRING string)
Pointer to function that returns a copy of the string in printable form without any control characters in it.
pANTLR3_VECTOR strings
List of all the strings that have been allocated by the factory.
Field Documentation
void(* ANTLR3_STRING_FACTORY_struct::close)(struct ANTLR3_STRING_FACTORY_struct *factory)
Pointer to function that closes the factory.
Referenced by antlr3InputClose(), and antlr3StringFactoryNew().
void(* ANTLR3_STRING_FACTORY_struct::destroy)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_STRING string)
Pointer to function that deletes the string altogether.
Referenced by antlr3StringFactoryNew().
ANTLR3_UINT32 ANTLR3_STRING_FACTORY_struct::index
Referenced by antlr3StringFactoryNew(), destroy(), newRaw8(), and newRawUTF16().
pANTLR3_STRING(* ANTLR3_STRING_FACTORY_struct::newPtr)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string, ANTLR3_UINT32 size)
Pointer to function that manufactures a string from a given pointer and length.
The pointer is assumed to point to characters in the same encoding as the string type, hence if this is a UTF16 string the pointer should point to UTF16 characters.
Referenced by antlr38BitSubstr(), antlr3StringFactoryNew(), antlr3UTF16Substr(), antlr3UTF32Substr(), createTokenFromToken(), newStrUTF16_UTF16(), subString8(), subStringUTF16(), toString(), and toUTF8_8().
pANTLR3_STRING(* ANTLR3_STRING_FACTORY_struct::newPtr8)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string, ANTLR3_UINT32 size)
Pointer to function that manufactures a string from a given pointer and length.
The pointer is assumed to point at 8 bit characters which must be converted on the fly to the encoding of the actual string.
Referenced by antlr3StringFactoryNew(), newStr8(), and newStrUTF16_8().
pANTLR3_STRING(* ANTLR3_STRING_FACTORY_struct::newRaw)(struct ANTLR3_STRING_FACTORY_struct *factory)
Pointer to function that manufactures an empty string.
Referenced by antlr3StringFactoryNew(), newSize8(), newSizeUTF16(), toString(), toStringSS(), and toStringTree().
pANTLR3_STRING(* ANTLR3_STRING_FACTORY_struct::newSize)(struct ANTLR3_STRING_FACTORY_struct *factory, ANTLR3_UINT32 size)
Pointer to function that manufactures a raw string with no text in it but space for size characters.
Referenced by antlr3StringFactoryNew(), newPtr8(), newPtrUTF16_8(), newPtrUTF16_UTF16(), printable8(), printableUTF16(), serializeNode(), and serializeToken().
pANTLR3_STRING(* ANTLR3_STRING_FACTORY_struct::newStr)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string)
Pointer to function that manufactures a string from a given pointer and works out the length.
The pointer is assumed to point to characters in the same encoding as the string itself, i.e. UTF16 if a UTF16 string and so on.
Referenced by antlr38BitReuse(), and antlr3StringFactoryNew().
pANTLR3_STRING(* ANTLR3_STRING_FACTORY_struct::newStr8)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_UINT8 string)
Pointer to function that manufactures a string from a given pointer and length.
The pointer should point to 8 bit characters regardless of the actual encoding of the string. The 8 bit characters will be converted to the actual string encoding on the fly.
Referenced by antlr3FileStreamNew(), antlr3StringFactoryNew(), antlr3StringStreamNew(), getText(), makeDot(), and toUTF8_UTF16().
pANTLR3_STRING(* ANTLR3_STRING_FACTORY_struct::printable)(struct ANTLR3_STRING_FACTORY_struct *factory, pANTLR3_STRING string)
Pointer to function that returns a copy of the string in printable form without any control characters in it.
Referenced by antlr3StringFactoryNew().
pANTLR3_VECTOR ANTLR3_STRING_FACTORY_struct::strings
List of all the strings that have been allocated by the factory.
Referenced by antlr3StringFactoryNew(), closeFactory(), destroy(), newRaw8(), and newRawUTF16().
The documentation for this struct was generated from the following file:
include/antlr3string.h