ANTLR3C: ANTLR3_LIST_struct Struct Reference
ANTLR3_LIST_struct Struct Reference
#include <antlr3collections.h>
Detailed Description
Structure that represents a LIST collection.
Data Fields
ANTLR3_INT32(* add)(struct ANTLR3_LIST_struct *list, void *element, void(ANTLR3_CDECL *freeptr)(void *))
void(* del)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key)
void(* free)(struct ANTLR3_LIST_struct *list)
void *(* get)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key)
ANTLR3_INT32(* put)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key, void *element, void(ANTLR3_CDECL *freeptr)(void *))
void *(* remove)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key)
ANTLR3_UINT32(* size)(struct ANTLR3_LIST_struct *list)
pANTLR3_HASH_TABLE table
Hash table that is storing the list elements.
Field Documentation
ANTLR3_INT32(* ANTLR3_LIST_struct::add)(struct ANTLR3_LIST_struct *list, void *element, void(ANTLR3_CDECL *freeptr)(void *))
Referenced by antlr3ListNew().
void(* ANTLR3_LIST_struct::del)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key)
Referenced by antlr3ListNew().
void(* ANTLR3_LIST_struct::free)(struct ANTLR3_LIST_struct *list)
Referenced by antlr3CTSFree(), antlr3ListNew(), getTokensSet(), and reset().
void*(* ANTLR3_LIST_struct::get)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key)
Referenced by addChildren(), and antlr3ListNew().
ANTLR3_INT32(* ANTLR3_LIST_struct::put)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key, void *element, void(ANTLR3_CDECL *freeptr)(void *))
Referenced by antlr3ListAdd(), antlr3ListNew(), discardTokenType(), getTokensSet(), and setTokenTypeChannel().
void*(* ANTLR3_LIST_struct::remove)(struct ANTLR3_LIST_struct *list, ANTLR3_INTKEY key)
Referenced by antlr3ListNew().
ANTLR3_UINT32(* ANTLR3_LIST_struct::size)(struct ANTLR3_LIST_struct *list)
Referenced by addChildren(), antlr3ListNew(), and getTokensSet().
pANTLR3_HASH_TABLE ANTLR3_LIST_struct::table
Hash table that is storing the list elements.
Referenced by antlr3ListAdd(), antlr3ListDelete(), antlr3ListFree(), antlr3ListGet(), antlr3ListNew(), antlr3ListPut(), antlr3ListRemove(), antlr3ListSize(), and getTokensList().
The documentation for this struct was generated from the following file:
include/antlr3collections.h