#!/usr/bin/perl -n
$line = $_;
$len = length($line);
for ($i = 0; $i < $len; $i++) {
  my $chr = substr($line, $i, 1);
  if ($chr eq '(') {
    $indent++;
    if ($last_char_was_rparen) {
      $last_char_was_rparen = 0;
    } else {
      print "\n";
      print(' ' x $indent);
    }
    print $chr;
  } else {
    if ($chr eq ' ' && substr($line, $i+1, 1) eq ')') {
      print(' ') unless $last_char_was_rparen;
      print ")\n";
      $indent--;
      print(' ' x $indent);
      $last_char_was_rparen = 1;
      $i++;
    } else {
      print $chr;
      if ($chr ne ' ') {
        $last_char_was_rparen = 0;
      }
    }
  }
}
