.TH "include/antlr3parsetree.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3parsetree.h \- 
.SH "Detailed Description"
.PP 
Abstraction of Common tree to provide payload and string representation of node. 

\fBTodo\fP
.RS 4
May not need this in the end 
.RE
.PP

.SH SYNOPSIS
.br
.PP
\fC#include <antlr3basetree.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_PARSE_TREE_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_PARSE_TREE_struct\fP \fBANTLR3_PARSE_TREE\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_PARSE_TREE_struct\fP
     \fBANTLR3_PARSE_TREE\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
