.TH "ANTLR3_TRIE_ENTRY_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_TRIE_ENTRY_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3collections.h>\fP
.PP
.SH "Detailed Description"
.PP 
Structure that holds the payload entry in an ANTLR3_INT_TRIE or ANTLR3_STRING_TRIE. 
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP (ANTLR3_CDECL *freeptr)(void *)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBANTLR3_INTKEY\fP \fBintVal\fP"
.br
.ti -1c
.RI "   void * \fBptr\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.ti -1c
.RI "struct \fBANTLR3_TRIE_ENTRY_struct\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP \fBtype\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "ANTLR3_TRIE_ENTRY_struct::void (ANTLR3_CDECL * freeptr)"
.PP
.SH "Field Documentation"
.PP 
.SS "union { ... }   \fBANTLR3_TRIE_ENTRY_struct::data\fP"
.PP
Referenced by freeIntNode(), getRuleMemoization(), intTrieAdd(), and memoize().
.SS "\fBANTLR3_INTKEY\fP \fBANTLR3_TRIE_ENTRY_struct::intVal\fP"
.PP
Referenced by getRuleMemoization(), and intTrieAdd().
.SS "struct \fBANTLR3_TRIE_ENTRY_struct\fP* \fBANTLR3_TRIE_ENTRY_struct::next\fP\fC [read]\fP"
.PP
Referenced by freeIntNode(), and intTrieAdd().
.SS "void* \fBANTLR3_TRIE_ENTRY_struct::ptr\fP"
.PP
Referenced by freeIntNode(), getRuleMemoization(), intTrieAdd(), and memoize().
.SS "\fBANTLR3_UINT32\fP \fBANTLR3_TRIE_ENTRY_struct::type\fP"
.PP
Referenced by freeIntNode(), and intTrieAdd().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
