.TH "include/antlr3parser.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3parser.h \- 
.SH "Detailed Description"
.PP 
Base implementation of an ANTLR3 parser. 


.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br
\fC#include <antlr3baserecognizer.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_PARSER_struct\fP"
.br
.RI "\fIThis is the main interface for an ANTLR3 parser. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_PARSER_struct\fP \fBANTLR3_PARSER\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_PARSER_struct\fP
     \fBANTLR3_PARSER\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
