.TH "ANTLR3_REWRITE_RULE_ELEMENT_STREAM - Token Rewrite Stream Class Definition" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_REWRITE_RULE_ELEMENT_STREAM - Token Rewrite Stream Class Definition \- 
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP * \fBpANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP * \fBpANTLR3_REWRITE_RULE_TOKEN_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP* \fBpANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP"
.PP
Pointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP. 
.PP
.SS "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP* \fBpANTLR3_REWRITE_RULE_TOKEN_STREAM\fP"
.PP
Pointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP. 
.PP

