.TH "ANTLR3_STACK_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_STACK_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3collections.h>\fP
.PP
.SH "Detailed Description"
.PP 
Structure that represents a Stack collection. 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBfree\fP )(struct \fBANTLR3_STACK_struct\fP *stack)"
.br
.ti -1c
.RI "void *(* \fBget\fP )(struct \fBANTLR3_STACK_struct\fP *stack, \fBANTLR3_INTKEY\fP key)"
.br
.ti -1c
.RI "void *(* \fBpeek\fP )(struct \fBANTLR3_STACK_struct\fP *stack)"
.br
.ti -1c
.RI "void *(* \fBpop\fP )(struct \fBANTLR3_STACK_struct\fP *stack)"
.br
.ti -1c
.RI "\fBANTLR3_BOOLEAN\fP(* \fBpush\fP )(struct \fBANTLR3_STACK_struct\fP *stack, void *element, void(ANTLR3_CDECL *freeptr)(void *))"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP(* \fBsize\fP )(struct \fBANTLR3_STACK_struct\fP *stack)"
.br
.ti -1c
.RI "void * \fBtop\fP"
.br
.RI "\fIUsed for quick access to the top of the stack. \fP"
.ti -1c
.RI "\fBpANTLR3_VECTOR\fP \fBvector\fP"
.br
.RI "\fIList that supports the stack structure. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "void(* \fBANTLR3_STACK_struct::free\fP)(struct \fBANTLR3_STACK_struct\fP *stack)"
.PP
Referenced by antlr3CommonTreeNodeStreamFree(), antlr3StackNew(), closeVectorFactory(), factoryClose(), freeLexer(), freeParser(), and reset().
.SS "void*(* \fBANTLR3_STACK_struct::get\fP)(struct \fBANTLR3_STACK_struct\fP *stack, \fBANTLR3_INTKEY\fP key)"
.PP
Referenced by antlr3StackNew(), and combineFollows().
.SS "void*(* \fBANTLR3_STACK_struct::peek\fP)(struct \fBANTLR3_STACK_struct\fP *stack)"
.PP
Referenced by antlr3StackNew(), newPoolTree(), and newVector().
.SS "void*(* \fBANTLR3_STACK_struct::pop\fP)(struct \fBANTLR3_STACK_struct\fP *stack)"
.PP
Referenced by antlr3StackNew(), newPoolTree(), newVector(), and popCharStream().
.SS "\fBANTLR3_BOOLEAN\fP(* \fBANTLR3_STACK_struct::push\fP)(struct \fBANTLR3_STACK_struct\fP *stack, void *element, void(ANTLR3_CDECL *freeptr)(void *))"
.PP
Referenced by antlr3StackNew(), pushCharStream(), returnVector(), and reuse().
.SS "\fBANTLR3_UINT32\fP(* \fBANTLR3_STACK_struct::size\fP)(struct \fBANTLR3_STACK_struct\fP *stack)"
.PP
Referenced by antlr3StackNew(), combineFollows(), nextToken(), and popCharStream().
.SS "void* \fBANTLR3_STACK_struct::top\fP"
.PP
Used for quick access to the top of the stack. 
.PP
Referenced by antlr3StackFree(), antlr3StackNew(), antlr3StackPeek(), antlr3StackPop(), antlr3StackPush(), and popCharStream().
.SS "\fBpANTLR3_VECTOR\fP \fBANTLR3_STACK_struct::vector\fP"
.PP
List that supports the stack structure. 
.PP
Referenced by antlr3StackFree(), antlr3StackGet(), antlr3StackNew(), antlr3StackPop(), antlr3StackPush(), antlr3StackSize(), and mismatchIsMissingToken().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
