.TH "ANTLR3_HASH_KEY_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_HASH_KEY_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3collections.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBANTLR3_INTKEY\fP \fBiKey\fP"
.br
.RI "\fIused if type is ANTLR3_HASH_TYPE_INT \fP"
.ti -1c
.RI "   \fBpANTLR3_UINT8\fP \fBsKey\fP"
.br
.RI "\fIUsed if type is ANTLR3_HASH_TYPE_STR. \fP"
.ti -1c
.RI "} \fBkey\fP"
.br
.ti -1c
.RI "\fBANTLR3_UINT8\fP \fBtype\fP"
.br
.RI "\fIOne of #\fBANTLR3_HASH_TYPE_INT\fP or #\fBANTLR3_HASH_TYPE_STR\fP. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBANTLR3_INTKEY\fP \fBANTLR3_HASH_KEY_struct::iKey\fP"
.PP
used if type is ANTLR3_HASH_TYPE_INT 
.PP
Referenced by antlr3HashGetI(), antlr3HashPutI(), and antlr3HashRemoveI().
.SS "union { ... } 
	 \fBANTLR3_HASH_KEY_struct::key\fP"
.PP
Referenced by antlr3HashFree(), antlr3HashGet(), antlr3HashGetI(), antlr3HashPut(), antlr3HashPutI(), antlr3HashRemove(), and antlr3HashRemoveI().
.SS "\fBpANTLR3_UINT8\fP \fBANTLR3_HASH_KEY_struct::sKey\fP"
.PP
Used if type is ANTLR3_HASH_TYPE_STR. 
.PP
Referenced by antlr3HashFree(), antlr3HashGet(), antlr3HashPut(), and antlr3HashRemove().
.SS "\fBANTLR3_UINT8\fP \fBANTLR3_HASH_KEY_struct::type\fP"
.PP
One of #\fBANTLR3_HASH_TYPE_INT\fP or #\fBANTLR3_HASH_TYPE_STR\fP. 
.PP
Referenced by antlr3HashFree(), antlr3HashPut(), and antlr3HashPutI().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
