.TH "ANTLR3_HASH_ENUM_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_HASH_ENUM_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3collections.h>\fP
.PP
.SH "Detailed Description"
.PP 
Internal structure representing an enumeration of a table. 

This is returned by antlr3Enumeration() Allows the programmer to traverse the table in hash order without knowing what is in the actual table.
.PP
Note that it is up to the caller to ensure that the table structure does not change in the hash bucket that is currently being enumerated as this structure just tracks the next pointers in the bucket series. 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBANTLR3_UINT32\fP \fBbucket\fP"
.br
.ti -1c
.RI "\fBpANTLR3_HASH_ENTRY\fP \fBentry\fP"
.br
.ti -1c
.RI "void(* \fBfree\fP )(struct \fBANTLR3_HASH_ENUM_struct\fP *\fBtable\fP)"
.br
.ti -1c
.RI "int(* \fBnext\fP )(struct \fBANTLR3_HASH_ENUM_struct\fP *en, \fBpANTLR3_HASH_KEY\fP *key, void **data)"
.br
.ti -1c
.RI "\fBpANTLR3_HASH_TABLE\fP \fBtable\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBANTLR3_UINT32\fP \fBANTLR3_HASH_ENUM_struct::bucket\fP"
.PP
Referenced by antlr3EnumNew(), antlr3EnumNext(), and antlr3EnumNextEntry().
.SS "\fBpANTLR3_HASH_ENTRY\fP \fBANTLR3_HASH_ENUM_struct::entry\fP"
.PP
Referenced by antlr3EnumNew(), antlr3EnumNext(), and antlr3EnumNextEntry().
.SS "void(* \fBANTLR3_HASH_ENUM_struct::free\fP)(struct \fBANTLR3_HASH_ENUM_struct\fP *\fBtable\fP)"
.PP
Referenced by antlr3BitsetList(), and antlr3EnumNew().
.SS "int(* \fBANTLR3_HASH_ENUM_struct::next\fP)(struct \fBANTLR3_HASH_ENUM_struct\fP *en, \fBpANTLR3_HASH_KEY\fP *key, void **data)"
.PP
Referenced by antlr3BitsetList(), and antlr3EnumNew().
.SS "\fBpANTLR3_HASH_TABLE\fP \fBANTLR3_HASH_ENUM_struct::table\fP"
.PP
Referenced by antlr3EnumNew(), antlr3EnumNext(), and antlr3EnumNextEntry().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
