.TH "include/antlr3tokenstream.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3tokenstream.h \- 
.SH "Detailed Description"
.PP 
Defines the interface for an ANTLR3 common token stream. 

Custom token streams should create one of these and then override any functions by installing their own pointers to implement the various functions. 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br
\fC#include <antlr3string.h>\fP
.br
\fC#include <antlr3collections.h>\fP
.br
\fC#include <antlr3input.h>\fP
.br
\fC#include <antlr3commontoken.h>\fP
.br
\fC#include <antlr3bitset.h>\fP
.br
\fC#include <antlr3debugeventlistener.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_COMMON_TOKEN_STREAM_struct\fP"
.br
.RI "\fICommon token stream is an implementation of ANTLR_TOKEN_STREAM for the default parsers and recognizers. \fP"
.ti -1c
.RI "struct \fBANTLR3_TOKEN_SOURCE_struct\fP"
.br
.RI "\fIDefinition of a token source, which has a pointer to a function that returns the next token (using a token factory if it is going to be efficient) and a pointer to an ANTLR3_INPUT_STREAM. \fP"
.ti -1c
.RI "struct \fBANTLR3_TOKEN_STREAM_struct\fP"
.br
.RI "\fIDefinition of the ANTLR3 common token stream interface. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TOKEN_STREAM_struct\fP \fBANTLR3_COMMON_TOKEN_STREAM\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_TOKEN_SOURCE_struct\fP \fBANTLR3_TOKEN_SOURCE\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_TOKEN_STREAM_struct\fP \fBANTLR3_TOKEN_STREAM\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_COMMON_TOKEN_STREAM_struct\fP
     \fBANTLR3_COMMON_TOKEN_STREAM\fP"
.PP
.SS "typedef struct \fBANTLR3_TOKEN_SOURCE_struct\fP
     \fBANTLR3_TOKEN_SOURCE\fP"
.PP
.SS "typedef struct \fBANTLR3_TOKEN_STREAM_struct\fP
     \fBANTLR3_TOKEN_STREAM\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
