.TH "include/antlr3exception.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3exception.h \- 
.SH "Detailed Description"
.PP 
Contains the definition of a basic ANTLR3 exception structure created by a recognizer when errors are found/predicted. 


.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_EXCEPTION_struct\fP"
.br
.RI "\fIBase structure for an ANTLR3 exception tracker. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBANTLR3_EARLY_EXIT_EXCEPTION\fP   5"
.br
.ti -1c
.RI "#define \fBANTLR3_EARLY_EXIT_NAME\fP   'org.antlr.runtime.EarlyExitException'"
.br
.ti -1c
.RI "#define \fBANTLR3_FAILED_PREDICATE_EXCEPTION\fP   6"
.br
.ti -1c
.RI "#define \fBANTLR3_FAILED_PREDICATE_NAME\fP   'org.antlr.runtime.FailedPredicateException'"
.br
.ti -1c
.RI "#define \fBANTLR3_MISMATCHED_EX_NAME\fP   'org.antlr.runtime.MismatchedTokenException'"
.br
.RI "\fIName of \fBANTLR3_MISMATCHED_TOKEN_EXCEPTION\fP. \fP"
.ti -1c
.RI "#define \fBANTLR3_MISMATCHED_SET_EXCEPTION\fP   4"
.br
.ti -1c
.RI "#define \fBANTLR3_MISMATCHED_SET_NAME\fP   'org.antlr.runtime.MismatchedSetException'"
.br
.ti -1c
.RI "#define \fBANTLR3_MISMATCHED_TOKEN_EXCEPTION\fP   2"
.br
.RI "\fIIndicates that the recognizer was expecting one token and found a a different one. \fP"
.ti -1c
.RI "#define \fBANTLR3_MISMATCHED_TREE_NODE_EXCEPTION\fP   7"
.br
.ti -1c
.RI "#define \fBANTLR3_MISMATCHED_TREE_NODE_NAME\fP   'org.antlr.runtime.MismatchedTreeNodeException'"
.br
.ti -1c
.RI "#define \fBANTLR3_MISSING_TOKEN_EXCEPTION\fP   10"
.br
.ti -1c
.RI "#define \fBANTLR3_MISSING_TOKEN_EXCEPTION_NAME\fP   'org.antlr.runtime.MissingTokenException'"
.br
.ti -1c
.RI "#define \fBANTLR3_NO_VIABLE_ALT_EXCEPTION\fP   3"
.br
.RI "\fIRecognizer could not find a valid alternative from the input. \fP"
.ti -1c
.RI "#define \fBANTLR3_NO_VIABLE_ALT_NAME\fP   'org.antlr.runtime.NoViableAltException'"
.br
.RI "\fIName of \fBANTLR3_NO_VIABLE_ALT_EXCEPTION\fP. \fP"
.ti -1c
.RI "#define \fBANTLR3_RECOGNITION_EX_NAME\fP   'org.antlr.runtime.RecognitionException'"
.br
.RI "\fIName of exception \fBANTLR3_RECOGNITION_EXCEPTION\fP. \fP"
.ti -1c
.RI "#define \fBANTLR3_RECOGNITION_EXCEPTION\fP   1"
.br
.RI "\fIIndicates that the recognizer received a token in the input that was not predicted. \fP"
.ti -1c
.RI "#define \fBANTLR3_REWRITE_EARLY_EXCEPTION\fP   8"
.br
.ti -1c
.RI "#define \fBANTLR3_REWRITE_EARLY_EXCEPTION_NAME\fP   'org.antlr.runtime.tree.RewriteEarlyExitException'"
.br
.ti -1c
.RI "#define \fBANTLR3_UNWANTED_TOKEN_EXCEPTION\fP   9"
.br
.ti -1c
.RI "#define \fBANTLR3_UNWANTED_TOKEN_EXCEPTION_NAME\fP   'org.antlr.runtime.UnwantedTokenException'"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_EXCEPTION_struct\fP \fBANTLR3_EXCEPTION\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ANTLR3_EARLY_EXIT_EXCEPTION   5"
.PP
Referenced by displayRecognitionError().
.SS "#define ANTLR3_EARLY_EXIT_NAME   'org.antlr.runtime.EarlyExitException'"
.PP
.SS "#define ANTLR3_FAILED_PREDICATE_EXCEPTION   6"
.PP
.SS "#define ANTLR3_FAILED_PREDICATE_NAME   'org.antlr.runtime.FailedPredicateException'"
.PP
.SS "#define ANTLR3_MISMATCHED_EX_NAME   'org.antlr.runtime.MismatchedTokenException'"
.PP
Name of \fBANTLR3_MISMATCHED_TOKEN_EXCEPTION\fP. 
.PP
Referenced by antlr3MTExceptionNew().
.SS "#define ANTLR3_MISMATCHED_SET_EXCEPTION   4"
.PP
Referenced by displayRecognitionError().
.SS "#define ANTLR3_MISMATCHED_SET_NAME   'org.antlr.runtime.MismatchedSetException'"
.PP
.SS "#define ANTLR3_MISMATCHED_TOKEN_EXCEPTION   2"
.PP
Indicates that the recognizer was expecting one token and found a a different one. 
.PP
Referenced by antlr3MTExceptionNew(), and displayRecognitionError().
.SS "#define ANTLR3_MISMATCHED_TREE_NODE_EXCEPTION   7"
.PP
Referenced by antlr3MTNExceptionNew().
.SS "#define ANTLR3_MISMATCHED_TREE_NODE_NAME   'org.antlr.runtime.MismatchedTreeNodeException'"
.PP
Referenced by antlr3MTNExceptionNew().
.SS "#define ANTLR3_MISSING_TOKEN_EXCEPTION   10"
.PP
Referenced by displayRecognitionError(), mismatch(), recoverFromMismatchedSet(), and recoverFromMismatchedToken().
.SS "#define ANTLR3_MISSING_TOKEN_EXCEPTION_NAME   'org.antlr.runtime.MissingTokenException'"
.PP
Referenced by mismatch(), and recoverFromMismatchedToken().
.SS "#define ANTLR3_NO_VIABLE_ALT_EXCEPTION   3"
.PP
Recognizer could not find a valid alternative from the input. 
.PP
Referenced by displayRecognitionError(), and noViableAlt().
.SS "#define ANTLR3_NO_VIABLE_ALT_NAME   'org.antlr.runtime.NoViableAltException'"
.PP
Name of \fBANTLR3_NO_VIABLE_ALT_EXCEPTION\fP. 
.PP
.SS "#define ANTLR3_RECOGNITION_EX_NAME   'org.antlr.runtime.RecognitionException'"
.PP
Name of exception \fBANTLR3_RECOGNITION_EXCEPTION\fP. 
.PP
Referenced by antlr3RecognitionExceptionNew().
.SS "#define ANTLR3_RECOGNITION_EXCEPTION   1"
.PP
Indicates that the recognizer received a token in the input that was not predicted. 
.PP
Referenced by antlr3RecognitionExceptionNew(), and displayRecognitionError().
.SS "#define ANTLR3_REWRITE_EARLY_EXCEPTION   8"
.PP
.SS "#define ANTLR3_REWRITE_EARLY_EXCEPTION_NAME   'org.antlr.runtime.tree.RewriteEarlyExitException'"
.PP
.SS "#define ANTLR3_UNWANTED_TOKEN_EXCEPTION   9"
.PP
Referenced by displayRecognitionError(), mismatch(), and recoverFromMismatchedToken().
.SS "#define ANTLR3_UNWANTED_TOKEN_EXCEPTION_NAME   'org.antlr.runtime.UnwantedTokenException'"
.PP
Referenced by mismatch(), and recoverFromMismatchedToken().
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_EXCEPTION_struct\fP
     \fBANTLR3_EXCEPTION\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
