.TH "ANTLR3_VECTOR_ELEMENT_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_VECTOR_ELEMENT_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3collections.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP (ANTLR3_CDECL *freeptr)(void *)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBelement\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "ANTLR3_VECTOR_ELEMENT_struct::void (ANTLR3_CDECL * freeptr)"
.PP
.SH "Field Documentation"
.PP 
.SS "void* \fBANTLR3_VECTOR_ELEMENT_struct::element\fP"
.PP
Referenced by antlr3VectorAdd(), antlr3VectorClear(), antlr3VectorDel(), antlr3VectorFree(), antlr3VectorGet(), antlr3VectorSet(), antlr3VectorSwap(), antrl3VectorRemove(), destroy(), freeNodeRS(), LB(), and tokLT().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
