.TH "ANTLR3_COMMON_TREE_ADAPTOR_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_COMMON_TREE_ADAPTOR_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3commontreeadaptor.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpANTLR3_ARBORETUM\fP \fBarboretum\fP"
.br
.RI "\fITree factory for producing new nodes as required without needing to track memory allocation per node. \fP"
.ti -1c
.RI "\fBANTLR3_TREE_ADAPTOR\fP \fBbaseAdaptor\fP"
.br
.RI "\fIBase interface implementation, embedded structure. \fP"
.ti -1c
.RI "void * \fBsuper\fP"
.br
.RI "\fIAny enclosing structure/class can use this pointer to point to its own interface. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpANTLR3_ARBORETUM\fP \fBANTLR3_COMMON_TREE_ADAPTOR_struct::arboretum\fP"
.PP
Tree factory for producing new nodes as required without needing to track memory allocation per node. 
.PP
Referenced by ANTLR3_TREE_ADAPTORNew(), and ctaFree().
.SS "\fBANTLR3_TREE_ADAPTOR\fP \fBANTLR3_COMMON_TREE_ADAPTOR_struct::baseAdaptor\fP"
.PP
Base interface implementation, embedded structure. 
.PP
Referenced by ANTLR3_TREE_ADAPTORNew().
.SS "void* \fBANTLR3_COMMON_TREE_ADAPTOR_struct::super\fP"
.PP
Any enclosing structure/class can use this pointer to point to its own interface. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
