.TH "include/antlr3commontreenodestream.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3commontreenodestream.h \- 
.SH "Detailed Description"
.PP 
Definition of the ANTLR3 common tree node stream. 


.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br
\fC#include <antlr3commontreeadaptor.h>\fP
.br
\fC#include <antlr3commontree.h>\fP
.br
\fC#include <antlr3collections.h>\fP
.br
\fC#include <antlr3intstream.h>\fP
.br
\fC#include <antlr3string.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_COMMON_TREE_NODE_STREAM_struct\fP"
.br
.ti -1c
.RI "struct \fBANTLR3_TREE_NODE_STREAM_struct\fP"
.br
.ti -1c
.RI "struct \fBANTLR3_TREE_WALK_STATE_struct\fP"
.br
.RI "\fIThis structure is used to save the state information in the treenodestream when walking ahead with cyclic DFA or for syntactic predicates, we need to record the state of the tree node stream. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_INITIAL_BUFFER_SIZE\fP   100"
.br
.RI "\fIToken buffer initial size settings ( will auto increase). \fP"
.ti -1c
.RI "#define \fBINITIAL_CALL_STACK_SIZE\fP   10"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TREE_NODE_STREAM_struct\fP \fBANTLR3_COMMON_TREE_NODE_STREAM\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_TREE_NODE_STREAM_struct\fP \fBANTLR3_TREE_NODE_STREAM\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_TREE_WALK_STATE_struct\fP \fBANTLR3_TREE_WALK_STATE\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DEFAULT_INITIAL_BUFFER_SIZE   100"
.PP
Token buffer initial size settings ( will auto increase). 
.PP
Referenced by antlr3CommonTreeNodeStreamNew(), and antlr3CommonTreeNodeStreamNewStream().
.SS "#define INITIAL_CALL_STACK_SIZE   10"
.PP
Referenced by antlr3CommonTreeNodeStreamNew(), and reset().
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_COMMON_TREE_NODE_STREAM_struct\fP
     \fBANTLR3_COMMON_TREE_NODE_STREAM\fP"
.PP
.SS "typedef struct \fBANTLR3_TREE_NODE_STREAM_struct\fP
     \fBANTLR3_TREE_NODE_STREAM\fP"
.PP
.SS "typedef struct \fBANTLR3_TREE_WALK_STATE_struct\fP
     \fBANTLR3_TREE_WALK_STATE\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
