.TH "src/antlr3parser.c" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/antlr3parser.c \- 
.SH "Detailed Description"
.PP 
Implementation of the base functionality for an ANTLR3 parser. 


.SH SYNOPSIS
.br
.PP
\fC#include <antlr3parser.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ANTLR3_API \fBpANTLR3_PARSER\fP \fBantlr3ParserNew\fP (\fBANTLR3_UINT32\fP sizeHint, \fBpANTLR3_RECOGNIZER_SHARED_STATE\fP state)"
.br
.ti -1c
.RI "ANTLR3_API \fBpANTLR3_PARSER\fP \fBantlr3ParserNewStream\fP (\fBANTLR3_UINT32\fP sizeHint, \fBpANTLR3_TOKEN_STREAM\fP tstream, \fBpANTLR3_RECOGNIZER_SHARED_STATE\fP state)"
.br
.ti -1c
.RI "ANTLR3_API \fBpANTLR3_PARSER\fP \fBantlr3ParserNewStreamDbg\fP (\fBANTLR3_UINT32\fP sizeHint, \fBpANTLR3_TOKEN_STREAM\fP tstream, \fBpANTLR3_DEBUG_EVENT_LISTENER\fP dbg, \fBpANTLR3_RECOGNIZER_SHARED_STATE\fP state)"
.br
.ti -1c
.RI "static void \fBfreeParser\fP (\fBpANTLR3_PARSER\fP parser)"
.br
.ti -1c
.RI "static \fBpANTLR3_TOKEN_STREAM\fP \fBgetTokenStream\fP (\fBpANTLR3_PARSER\fP parser)"
.br
.ti -1c
.RI "static void \fBsetDebugListener\fP (\fBpANTLR3_PARSER\fP parser, \fBpANTLR3_DEBUG_EVENT_LISTENER\fP dbg)"
.br
.ti -1c
.RI "static void \fBsetTokenStream\fP (\fBpANTLR3_PARSER\fP parser, \fBpANTLR3_TOKEN_STREAM\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ANTLR3_API \fBpANTLR3_PARSER\fP antlr3ParserNew (\fBANTLR3_UINT32\fP sizeHint, \fBpANTLR3_RECOGNIZER_SHARED_STATE\fP state)"
.PP
References ANTLR3_MALLOC, ANTLR3_TYPE_PARSER, antlr3BaseRecognizerNew(), antlr3MTExceptionNew(), ANTLR3_BASE_RECOGNIZER_struct::exConstruct, ANTLR3_PARSER_struct::free, freeParser(), getTokenStream(), ANTLR3_PARSER_struct::getTokenStream, ANTLR3_PARSER_struct::rec, setDebugListener(), ANTLR3_PARSER_struct::setDebugListener, setTokenStream(), ANTLR3_PARSER_struct::setTokenStream, and ANTLR3_BASE_RECOGNIZER_struct::super.
.PP
Referenced by antlr3ParserNewStream().
.SS "ANTLR3_API \fBpANTLR3_PARSER\fP antlr3ParserNewStream (\fBANTLR3_UINT32\fP sizeHint, \fBpANTLR3_TOKEN_STREAM\fP tstream, \fBpANTLR3_RECOGNIZER_SHARED_STATE\fP state)"
.PP
References antlr3ParserNew(), and ANTLR3_PARSER_struct::setTokenStream.
.PP
Referenced by antlr3ParserNewStreamDbg().
.SS "ANTLR3_API \fBpANTLR3_PARSER\fP antlr3ParserNewStreamDbg (\fBANTLR3_UINT32\fP sizeHint, \fBpANTLR3_TOKEN_STREAM\fP tstream, \fBpANTLR3_DEBUG_EVENT_LISTENER\fP dbg, \fBpANTLR3_RECOGNIZER_SHARED_STATE\fP state)"
.PP
References antlr3ParserNewStream(), and ANTLR3_PARSER_struct::setDebugListener.
.SS "static void freeParser (\fBpANTLR3_PARSER\fP parser)\fC [static]\fP"
.PP
References ANTLR3_FREE, ANTLR3_RECOGNIZER_SHARED_STATE_struct::following, ANTLR3_BASE_RECOGNIZER_struct::free, ANTLR3_STACK_struct::free, ANTLR3_PARSER_struct::rec, and ANTLR3_BASE_RECOGNIZER_struct::state.
.PP
Referenced by antlr3ParserNew(), and antlr3TreeParserNewStream().
.SS "static \fBpANTLR3_TOKEN_STREAM\fP getTokenStream (\fBpANTLR3_PARSER\fP parser)\fC [static]\fP"
.PP
References ANTLR3_PARSER_struct::tstream.
.PP
Referenced by antlr3ParserNew().
.SS "static void setDebugListener (\fBpANTLR3_PARSER\fP parser, \fBpANTLR3_DEBUG_EVENT_LISTENER\fP dbg)\fC [static]\fP"
.PP
References ANTLR3_BASE_RECOGNIZER_struct::debugger, ANTLR3_PARSER_struct::rec, ANTLR3_TOKEN_STREAM_struct::setDebugListener, and ANTLR3_PARSER_struct::tstream.
.PP
Referenced by antlr3CommonTokenStreamNew(), and antlr3ParserNew().
.SS "static void setTokenStream (\fBpANTLR3_PARSER\fP parser, \fBpANTLR3_TOKEN_STREAM\fP tstream)\fC [static]\fP"
.PP
References ANTLR3_PARSER_struct::rec, ANTLR3_BASE_RECOGNIZER_struct::reset, and ANTLR3_PARSER_struct::tstream.
.PP
Referenced by antlr3ParserNew().
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
