.TH "include/antlr3basetreeadaptor.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3basetreeadaptor.h \- 
.SH "Detailed Description"
.PP 
Definition of the ANTLR3 base tree adaptor. 


.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br
\fC#include <antlr3collections.h>\fP
.br
\fC#include <antlr3string.h>\fP
.br
\fC#include <antlr3basetree.h>\fP
.br
\fC#include <antlr3commontoken.h>\fP
.br
\fC#include <antlr3debugeventlistener.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_BASE_TREE_ADAPTOR_struct\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_TREE_ADAPTOR_struct\fP \fBANTLR3_TREE_ADAPTOR\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_TREE_ADAPTOR_struct\fP * \fBpANTLR3_TREE_ADAPTOR\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_BASE_TREE_ADAPTOR_struct\fP
     \fBANTLR3_TREE_ADAPTOR\fP"
.PP
.SS "typedef struct \fBANTLR3_BASE_TREE_ADAPTOR_struct\fP * \fBpANTLR3_TREE_ADAPTOR\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
