.TH "include/antlr3recognizersharedstate.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3recognizersharedstate.h \- 
.SH "Detailed Description"
.PP 
While the C runtime does not need to model the state of multiple lexers and parsers in the same way as the Java runtime does it is no overhead to reflect that model. 

In fact the C runtime has always been able to share recognizer state.
.PP
This 'class' therefore defines all the elements of a recognizer (either lexer, parser or tree parser) that are need to track the current recognition state. Multiple recognizers may then share this state, for instance when one grammar imports another. 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_RECOGNIZER_SHARED_STATE_struct\fP"
.br
.RI "\fIAll the data elements required to track the current state of any recognizer (lexer, parser, tree parser). \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_RECOGNIZER_SHARED_STATE_struct\fP \fBANTLR3_RECOGNIZER_SHARED_STATE\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_RECOGNIZER_SHARED_STATE_struct\fP
	 \fBANTLR3_RECOGNIZER_SHARED_STATE\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
