.TH "ANTLR3_HASH_BUCKET_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_HASH_BUCKET_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3collections.h>\fP
.PP
.SH "Detailed Description"
.PP 
Internal structure of a hash table bucket, which tracks all keys that hash to the same bucket. 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpANTLR3_HASH_ENTRY\fP \fBentries\fP"
.br
.RI "\fIPointer to the first entry in the bucket (if any, it may be NULL). \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpANTLR3_HASH_ENTRY\fP \fBANTLR3_HASH_BUCKET_struct::entries\fP"
.PP
Pointer to the first entry in the bucket (if any, it may be NULL). 
.PP
Duplicate entries are chained from here. 
.PP
Referenced by antlr3EnumNew(), antlr3EnumNextEntry(), antlr3HashFree(), antlr3HashGet(), antlr3HashGetI(), antlr3HashPut(), antlr3HashPutI(), antlr3HashRemove(), antlr3HashRemoveI(), and antlr3HashTableNew().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
