.TH "include/antlr3commontree.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3commontree.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br
\fC#include <antlr3basetree.h>\fP
.br
\fC#include <antlr3commontoken.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_ARBORETUM_struct\fP"
.br
.RI "\fIANTLR3 Tree factory interface to create lots of trees efficiently rather than creating and freeing lots of little bits of memory. \fP"
.ti -1c
.RI "struct \fBANTLR3_COMMON_TREE_struct\fP"
.br
.RI "\fIInterface for an ANTLR3 common tree which is what gets passed around by the AST producing parser. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_ARBORETUM_struct\fP \fBANTLR3_ARBORETUM\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TREE_struct\fP \fBANTLR3_COMMON_TREE\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_ARBORETUM_struct\fP
     \fBANTLR3_ARBORETUM\fP"
.PP
.SS "typedef struct \fBANTLR3_COMMON_TREE_struct\fP
     \fBANTLR3_COMMON_TREE\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
