.TH "include/antlr3baserecognizer.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3baserecognizer.h \- 
.SH "Detailed Description"
.PP 
Defines the basic structure to support recognizing by either a lexer, parser, or tree parser. 


.SH SYNOPSIS
.br
.PP
\fC#include <antlr3defs.h>\fP
.br
\fC#include <antlr3exception.h>\fP
.br
\fC#include <antlr3input.h>\fP
.br
\fC#include <antlr3tokenstream.h>\fP
.br
\fC#include <antlr3commontoken.h>\fP
.br
\fC#include <antlr3commontreenodestream.h>\fP
.br
\fC#include <antlr3debugeventlistener.h>\fP
.br
\fC#include <antlr3recognizersharedstate.h>\fP
.br
\fC#include <antlr3lexer.h>\fP
.br
\fC#include <antlr3parser.h>\fP
.br
\fC#include <antlr3treeparser.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_BASE_RECOGNIZER_struct\fP"
.br
.RI "\fIBase tracking context structure for all types of recognizers. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBANTLR3_TYPE_LEXER\fP   0x0001"
.br
.RI "\fIType indicator for a lexer recognizer. \fP"
.ti -1c
.RI "#define \fBANTLR3_TYPE_PARSER\fP   0x0002"
.br
.RI "\fIType indicator for a parser recognizer. \fP"
.ti -1c
.RI "#define \fBANTLR3_TYPE_TREE_PARSER\fP   0x0004"
.br
.RI "\fIType indicator for a tree parser recognizer. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_RECOGNIZER_struct\fP \fBANTLR3_BASE_RECOGNIZER\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
