.TH "ANTLR3_TREE_WALK_STATE_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_TREE_WALK_STATE_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3commontreenodestream.h>\fP
.PP
.SH "Detailed Description"
.PP 
This structure is used to save the state information in the treenodestream when walking ahead with cyclic DFA or for syntactic predicates, we need to record the state of the tree node stream. 

This class wraps up the current state of the CommonTreeNodeStream. Calling \fBmark()\fP will push another of these on the markers stack. 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBANTLR3_MARKER\fP \fBabsoluteNodeIndex\fP"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP \fBcurrentChildIndex\fP"
.br
.ti -1c
.RI "\fBpANTLR3_BASE_TREE\fP \fBcurrentNode\fP"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP \fBhead\fP"
.br
.ti -1c
.RI "\fBpANTLR3_BASE_TREE\fP * \fBlookAhead\fP"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP \fBlookAheadLength\fP"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP \fBnodeStackSize\fP"
.br
.ti -1c
.RI "\fBpANTLR3_BASE_TREE\fP \fBpreviousNode\fP"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP \fBtail\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBANTLR3_MARKER\fP \fBANTLR3_TREE_WALK_STATE_struct::absoluteNodeIndex\fP"
.PP
.SS "\fBANTLR3_UINT32\fP \fBANTLR3_TREE_WALK_STATE_struct::currentChildIndex\fP"
.PP
.SS "\fBpANTLR3_BASE_TREE\fP \fBANTLR3_TREE_WALK_STATE_struct::currentNode\fP"
.PP
.SS "\fBANTLR3_UINT32\fP \fBANTLR3_TREE_WALK_STATE_struct::head\fP"
.PP
.SS "\fBpANTLR3_BASE_TREE\fP* \fBANTLR3_TREE_WALK_STATE_struct::lookAhead\fP"
.PP
.SS "\fBANTLR3_UINT32\fP \fBANTLR3_TREE_WALK_STATE_struct::lookAheadLength\fP"
.PP
.SS "\fBANTLR3_UINT32\fP \fBANTLR3_TREE_WALK_STATE_struct::nodeStackSize\fP"
.PP
.SS "\fBpANTLR3_BASE_TREE\fP \fBANTLR3_TREE_WALK_STATE_struct::previousNode\fP"
.PP
.SS "\fBANTLR3_UINT32\fP \fBANTLR3_TREE_WALK_STATE_struct::tail\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
