.TH "include/antlr3cyclicdfa.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3cyclicdfa.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3baserecognizer.h>\fP
.br
\fC#include <antlr3intstream.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_CYCLIC_DFA_struct\fP"
.br
.RI "\fIDefinition of a cyclic dfa structure such that it can be initialized at compile time and have only a single runtime function that can deal with all cyclic dfa structures and show Java how it is done ;-). \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_CYCLIC_DFA_struct\fP \fBANTLR3_CYCLIC_DFA\fP"
.br
.ti -1c
.RI "typedef \fBANTLR3_INT32\fP(* \fBCDFA_SPECIAL_FUNC\fP )(void *, \fBpANTLR3_BASE_RECOGNIZER\fP, \fBpANTLR3_INT_STREAM\fP, struct \fBANTLR3_CYCLIC_DFA_struct\fP *, \fBANTLR3_INT32\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_CYCLIC_DFA_struct\fP
     \fBANTLR3_CYCLIC_DFA\fP"
.PP
.SS "typedef \fBANTLR3_INT32\fP(* \fBCDFA_SPECIAL_FUNC\fP)(void *, \fBpANTLR3_BASE_RECOGNIZER\fP, \fBpANTLR3_INT_STREAM\fP, struct \fBANTLR3_CYCLIC_DFA_struct\fP *, \fBANTLR3_INT32\fP)"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
