.TH "ANTLR3_BASE_RECOGNIZER - Base Recognizer Class Definition" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_BASE_RECOGNIZER - Base Recognizer Class Definition \- 
.SH "Detailed Description"
.PP 
This is the definition of the base recognizer interface, instantiations of which are referred to via \fBpANTLR3_BASE_RECOGNIZER\fP. 
.PP
In general you will not refer to one of these structures directly as a a \fBpANTLR3_BASE_RECOGNIZER\fP will be embedded within a higher level object such as \fBpANTLR3_PARSER\fP 
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBANTLR3_BASE_RECOGNIZER_struct\fP"
.br
.RI "\fIBase tracking context structure for all types of recognizers. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBANTLR3_TYPE_LEXER\fP   0x0001"
.br
.RI "\fIType indicator for a lexer recognizer. \fP"
.ti -1c
.RI "#define \fBANTLR3_TYPE_PARSER\fP   0x0002"
.br
.RI "\fIType indicator for a parser recognizer. \fP"
.ti -1c
.RI "#define \fBANTLR3_TYPE_TREE_PARSER\fP   0x0004"
.br
.RI "\fIType indicator for a tree parser recognizer. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_RECOGNIZER_struct\fP \fBANTLR3_BASE_RECOGNIZER\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_RECOGNIZER_struct\fP * \fBpANTLR3_BASE_RECOGNIZER\fP"
.br
.RI "\fIPointer to an instantiation of the 'class' \fBANTLR3_BASE_RECOGNIZER\fP. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define ANTLR3_TYPE_LEXER   0x0001"
.PP
Type indicator for a lexer recognizer. 
.PP
Referenced by alreadyParsedRule(), antlr3LexerNew(), antlr3RecognitionExceptionNew(), and memoize().
.SS "#define ANTLR3_TYPE_PARSER   0x0002"
.PP
Type indicator for a parser recognizer. 
.PP
Referenced by alreadyParsedRule(), antlr3ParserNew(), antlr3RecognitionExceptionNew(), antlr3TreeParserNewStream(), consumeUntil(), consumeUntilSet(), displayRecognitionError(), match(), matchAny(), memoize(), mismatch(), recover(), recoverFromMismatchedElement(), recoverFromMismatchedSet(), recoverFromMismatchedToken(), and synpred().
.SS "#define ANTLR3_TYPE_TREE_PARSER   0x0004"
.PP
Type indicator for a tree parser recognizer. 
.PP
Referenced by alreadyParsedRule(), antlr3RecognitionExceptionNew(), antlr3TreeParserNewStream(), consumeUntil(), consumeUntilSet(), displayRecognitionError(), match(), matchAny(), memoize(), recover(), recoverFromMismatchedElement(), recoverFromMismatchedSet(), recoverFromMismatchedToken(), and synpred().
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_BASE_RECOGNIZER_struct\fP
     \fBANTLR3_BASE_RECOGNIZER\fP"
.PP
.SS "typedef struct \fBANTLR3_BASE_RECOGNIZER_struct\fP* \fBpANTLR3_BASE_RECOGNIZER\fP"
.PP
Pointer to an instantiation of the 'class' \fBANTLR3_BASE_RECOGNIZER\fP. 
.PP

