.TH "ANTLR3_LIST_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_LIST_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3collections.h>\fP
.PP
.SH "Detailed Description"
.PP 
Structure that represents a LIST collection. 
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBANTLR3_INT32\fP(* \fBadd\fP )(struct \fBANTLR3_LIST_struct\fP *list, void *element, void(ANTLR3_CDECL *freeptr)(void *))"
.br
.ti -1c
.RI "void(* \fBdel\fP )(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key)"
.br
.ti -1c
.RI "void(* \fBfree\fP )(struct \fBANTLR3_LIST_struct\fP *list)"
.br
.ti -1c
.RI "void *(* \fBget\fP )(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key)"
.br
.ti -1c
.RI "\fBANTLR3_INT32\fP(* \fBput\fP )(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key, void *element, void(ANTLR3_CDECL *freeptr)(void *))"
.br
.ti -1c
.RI "void *(* \fBremove\fP )(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key)"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP(* \fBsize\fP )(struct \fBANTLR3_LIST_struct\fP *list)"
.br
.ti -1c
.RI "\fBpANTLR3_HASH_TABLE\fP \fBtable\fP"
.br
.RI "\fIHash table that is storing the list elements. \fP"
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBANTLR3_INT32\fP(* \fBANTLR3_LIST_struct::add\fP)(struct \fBANTLR3_LIST_struct\fP *list, void *element, void(ANTLR3_CDECL *freeptr)(void *))"
.PP
Referenced by antlr3ListNew().
.SS "void(* \fBANTLR3_LIST_struct::del\fP)(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key)"
.PP
Referenced by antlr3ListNew().
.SS "void(* \fBANTLR3_LIST_struct::free\fP)(struct \fBANTLR3_LIST_struct\fP *list)"
.PP
Referenced by antlr3CTSFree(), antlr3ListNew(), getTokensSet(), and reset().
.SS "void*(* \fBANTLR3_LIST_struct::get\fP)(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key)"
.PP
Referenced by addChildren(), and antlr3ListNew().
.SS "\fBANTLR3_INT32\fP(* \fBANTLR3_LIST_struct::put\fP)(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key, void *element, void(ANTLR3_CDECL *freeptr)(void *))"
.PP
Referenced by antlr3ListAdd(), antlr3ListNew(), discardTokenType(), getTokensSet(), and setTokenTypeChannel().
.SS "void*(* \fBANTLR3_LIST_struct::remove\fP)(struct \fBANTLR3_LIST_struct\fP *list, \fBANTLR3_INTKEY\fP key)"
.PP
Referenced by antlr3ListNew().
.SS "\fBANTLR3_UINT32\fP(* \fBANTLR3_LIST_struct::size\fP)(struct \fBANTLR3_LIST_struct\fP *list)"
.PP
Referenced by addChildren(), antlr3ListNew(), and getTokensSet().
.SS "\fBpANTLR3_HASH_TABLE\fP \fBANTLR3_LIST_struct::table\fP"
.PP
Hash table that is storing the list elements. 
.PP
Referenced by antlr3ListAdd(), antlr3ListDelete(), antlr3ListFree(), antlr3ListGet(), antlr3ListNew(), antlr3ListPut(), antlr3ListRemove(), antlr3ListSize(), and getTokensList().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
