.TH "ANTLR3_BITSET_struct" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ANTLR3_BITSET_struct \- 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3bitset.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void(* \fBadd\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_INT32\fP bit)"
.br
.ti -1c
.RI "\fBANTLR3_BITSET_LIST\fP \fBblist\fP"
.br
.RI "\fIThe actual bits themselves. \fP"
.ti -1c
.RI "\fBpANTLR3_BITSET\fP(* \fBbor\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset1, struct \fBANTLR3_BITSET_struct\fP *bitset2)"
.br
.ti -1c
.RI "void(* \fBborInPlace\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset, struct \fBANTLR3_BITSET_struct\fP *bitset2)"
.br
.ti -1c
.RI "\fBpANTLR3_BITSET\fP(* \fBclone\fP )(struct \fBANTLR3_BITSET_struct\fP *inSet)"
.br
.ti -1c
.RI "\fBANTLR3_BOOLEAN\fP(* \fBequals\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset1, struct \fBANTLR3_BITSET_struct\fP *bitset2)"
.br
.ti -1c
.RI "void(* \fBfree\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.br
.ti -1c
.RI "void(* \fBgrow\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_INT32\fP newSize)"
.br
.ti -1c
.RI "\fBANTLR3_BOOLEAN\fP(* \fBisMember\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_UINT32\fP bit)"
.br
.ti -1c
.RI "\fBANTLR3_BOOLEAN\fP(* \fBisNilNode\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP(* \fBnumBits\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.br
.ti -1c
.RI "void(* \fBremove\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_UINT32\fP bit)"
.br
.ti -1c
.RI "\fBANTLR3_UINT32\fP(* \fBsize\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.br
.ti -1c
.RI "\fBpANTLR3_INT32\fP(* \fBtoIntList\fP )(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "void(* \fBANTLR3_BITSET_struct::add\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_INT32\fP bit)"
.PP
Referenced by addEdge(), antlr3BitsetList(), antlr3BitsetSetAPI(), and DFS().
.SS "\fBANTLR3_BITSET_LIST\fP \fBANTLR3_BITSET_struct::blist\fP"
.PP
The actual bits themselves. 
.PP
Referenced by antlr3BitsetAdd(), antlr3BitsetClone(), antlr3BitsetCopy(), antlr3BitsetEquals(), antlr3BitsetFree(), antlr3BitsetIsNil(), antlr3BitsetLoad(), antlr3BitsetMember(), antlr3BitsetNew(), antlr3BitsetNumBits(), antlr3BitsetORInPlace(), antlr3BitsetRemove(), antlr3BitsetSize(), grow(), and growToInclude().
.SS "\fBpANTLR3_BITSET\fP(* \fBANTLR3_BITSET_struct::bor\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset1, struct \fBANTLR3_BITSET_struct\fP *bitset2)"
.PP
Referenced by antlr3BitsetSetAPI().
.SS "void(* \fBANTLR3_BITSET_struct::borInPlace\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset, struct \fBANTLR3_BITSET_struct\fP *bitset2)"
.PP
Referenced by antlr3BitsetSetAPI(), combineFollows(), and mismatchIsMissingToken().
.SS "\fBpANTLR3_BITSET\fP(* \fBANTLR3_BITSET_struct::clone\fP)(struct \fBANTLR3_BITSET_struct\fP *inSet)"
.PP
Referenced by antlr3BitsetSetAPI().
.SS "\fBANTLR3_BOOLEAN\fP(* \fBANTLR3_BITSET_struct::equals\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset1, struct \fBANTLR3_BITSET_struct\fP *bitset2)"
.PP
Referenced by antlr3BitsetSetAPI().
.SS "void(* \fBANTLR3_BITSET_struct::free\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.PP
Referenced by antlr3BitsetSetAPI(), combineFollows(), freeTopo(), getTokensList(), getTokensType(), mismatchIsMissingToken(), recover(), and recoverFromMismatchedElement().
.SS "void(* \fBANTLR3_BITSET_struct::grow\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_INT32\fP newSize)"
.PP
Referenced by antlr3BitsetLoad(), antlr3BitsetSetAPI(), and growToInclude().
.SS "\fBANTLR3_BOOLEAN\fP(* \fBANTLR3_BITSET_struct::isMember\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_UINT32\fP bit)"
.PP
Referenced by antlr3BitsetSetAPI(), antlr3BitsetToIntList(), combineFollows(), DFS(), getTokensSet(), mismatchIsMissingToken(), recoverFromMismatchedElement(), and sortToArray().
.SS "\fBANTLR3_BOOLEAN\fP(* \fBANTLR3_BITSET_struct::isNilNode\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.PP
Referenced by antlr3BitsetSetAPI().
.SS "\fBANTLR3_UINT32\fP(* \fBANTLR3_BITSET_struct::numBits\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.PP
Referenced by antlr3BitsetSetAPI(), antlr3BitsetToIntList(), DFS(), and displayRecognitionError().
.SS "void(* \fBANTLR3_BITSET_struct::remove\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset, \fBANTLR3_UINT32\fP bit)"
.PP
Referenced by antlr3BitsetSetAPI(), combineFollows(), mismatchIsMissingToken(), and recoverFromMismatchedElement().
.SS "\fBANTLR3_UINT32\fP(* \fBANTLR3_BITSET_struct::size\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.PP
Referenced by antlr3BitsetSetAPI(), antlr3BitsetToIntList(), DFS(), and displayRecognitionError().
.SS "\fBpANTLR3_INT32\fP(* \fBANTLR3_BITSET_struct::toIntList\fP)(struct \fBANTLR3_BITSET_struct\fP *bitset)"
.PP
Referenced by antlr3BitsetSetAPI().

.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
