.TH "src/antlr3intstream.c" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/antlr3intstream.c \- 
.SH "Detailed Description"
.PP 
Implementation of superclass elements of an ANTLR3 int stream. 

The only methods required are an allocator and a destructor. 
.SH SYNOPSIS
.br
.PP
\fC#include <antlr3intstream.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ANTLR3_API \fBpANTLR3_INT_STREAM\fP \fBantlr3IntStreamNew\fP ()"
.br
.ti -1c
.RI "static void \fBfreeStream\fP (\fBpANTLR3_INT_STREAM\fP stream)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
