.TH "include/antlr3interfaces.h" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/antlr3interfaces.h \- 
.SH "Detailed Description"
.PP 
Declarations for all the antlr3 C runtime interfaces/classes. 

This allows the structures that define the interfaces to contain pointers to each other without trying to sort out the cyclic interdependencies that would otherwise result. 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBANTLR3_ARBORETUM_struct\fP * \fBpANTLR3_ARBORETUM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_ARBORETUM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_RECOGNIZER_struct\fP * \fBpANTLR3_BASE_RECOGNIZER\fP"
.br
.RI "\fIPointer to an instantiation of the 'class' \fBANTLR3_BASE_RECOGNIZER\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_TREE_struct\fP * \fBpANTLR3_BASE_TREE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_BASE_TREE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_BASE_TREE_ADAPTOR_struct\fP * \fBpANTLR3_BASE_TREE_ADAPTOR\fP"
.br
.RI "\fIPointer to an instantiation of 'class' ANTLR3_BASE_TREE_ADAPTOR. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_BITSET_struct\fP * \fBpANTLR3_BITSET\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_BITSET\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_BITSET_LIST_struct\fP * \fBpANTLR3_BITSET_LIST\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_BITSET_LIST\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TOKEN_struct\fP * \fBpANTLR3_COMMON_TOKEN\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_COMMON_TOKEN\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TOKEN_STREAM_struct\fP * \fBpANTLR3_COMMON_TOKEN_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_COMMON_TOKEN_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TREE_struct\fP * \fBpANTLR3_COMMON_TREE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_COMMON_TREE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TREE_ADAPTOR_struct\fP * \fBpANTLR3_COMMON_TREE_ADAPTOR\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_COMMON_TREE_ADAPTOR\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_COMMON_TREE_NODE_STREAM_struct\fP * \fBpANTLR3_COMMON_TREE_NODE_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_COMMON_TREE_NODE_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_CYCLIC_DFA_struct\fP * \fBpANTLR3_CYCLIC_DFA\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_CYCLIC_DFA\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_DEBUG_EVENT_LISTENER_struct\fP * \fBpANTLR3_DEBUG_EVENT_LISTENER\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_DEBUG_EVENT_LISTENER\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_EXCEPTION_struct\fP * \fBpANTLR3_EXCEPTION\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_EXCEPTION\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_HASH_BUCKET_struct\fP * \fBpANTLR3_HASH_BUCKET\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_HASH_BUCKET\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_HASH_ENTRY_struct\fP * \fBpANTLR3_HASH_ENTRY\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_HASH_ENTRY\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_HASH_ENUM_struct\fP * \fBpANTLR3_HASH_ENUM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_HASH_ENUM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_HASH_TABLE_struct\fP * \fBpANTLR3_HASH_TABLE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_HASH_TABLE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_INPUT_STREAM_struct\fP * \fBpANTLR3_INPUT_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_INPUT_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_INT_STREAM_struct\fP * \fBpANTLR3_INT_STREAM\fP"
.br
.ti -1c
.RI "typedef struct \fBANTLR3_INT_TRIE_struct\fP * \fBpANTLR3_INT_TRIE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_INT_TRIE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_LEX_STATE_struct\fP * \fBpANTLR3_LEX_STATE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_LEX_STATE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_LEXER_struct\fP * \fBpANTLR3_LEXER\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_LEXER\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_LIST_struct\fP * \fBpANTLR3_LIST\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_LIST\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_PARSE_TREE_struct\fP * \fBpANTLR3_PARSE_TREE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_PARSE_TREE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_PARSER_struct\fP * \fBpANTLR3_PARSER\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_PARSER\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_RECOGNIZER_SHARED_STATE_struct\fP * \fBpANTLR3_RECOGNIZER_SHARED_STATE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_RECOGNIZER_SHARED_STATE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP * \fBpANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP * \fBpANTLR3_REWRITE_RULE_NODE_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_NODE_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP * \fBpANTLR3_REWRITE_RULE_SUBTREE_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' ANTLR3_REWRITE_RULE_SUBSTREE_STREAM. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP * \fBpANTLR3_REWRITE_RULE_TOKEN_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_STACK_struct\fP * \fBpANTLR3_STACK\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_STACK\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_STRING_struct\fP * \fBpANTLR3_STRING\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_STRING\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_STRING_FACTORY_struct\fP * \fBpANTLR3_STRING_FACTORY\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_STRING_FACTORY\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_TOKEN_FACTORY_struct\fP * \fBpANTLR3_TOKEN_FACTORY\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_TOKEN_FACTORY\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_TOKEN_SOURCE_struct\fP * \fBpANTLR3_TOKEN_SOURCE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_TOKEN_SOURCE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_TOKEN_STREAM_struct\fP * \fBpANTLR3_TOKEN_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_TOKEN_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_TOPO_struct\fP * \fBpANTLR3_TOPO\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_TOPO\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_TREE_NODE_STREAM_struct\fP * \fBpANTLR3_TREE_NODE_STREAM\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_TREE_NODE_STREAM\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_TREE_PARSER_struct\fP * \fBpANTLR3_TREE_PARSER\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_TREE_PARSER\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_TREE_WALK_STATE_struct\fP * \fBpANTLR3_TREE_WALK_STATE\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_TREE_WALK_STATE\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_VECTOR_struct\fP * \fBpANTLR3_VECTOR\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_VECTOR\fP. \fP"
.ti -1c
.RI "typedef struct \fBANTLR3_VECTOR_FACTORY_struct\fP * \fBpANTLR3_VECTOR_FACTORY\fP"
.br
.RI "\fIPointer to an instantiation of 'class' \fBANTLR3_VECTOR_FACTORY\fP. \fP"
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBANTLR3_BITSET_LIST_struct\fP* \fBpANTLR3_BITSET_LIST\fP"
.PP
Pointer to an instantiation of 'class' \fBANTLR3_BITSET_LIST\fP. 
.PP
.SS "typedef struct \fBANTLR3_INT_STREAM_struct\fP* \fBpANTLR3_INT_STREAM\fP"
.PP
.SS "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP* \fBpANTLR3_REWRITE_RULE_NODE_STREAM\fP"
.PP
Pointer to an instantiation of 'class' \fBANTLR3_REWRITE_RULE_NODE_STREAM\fP. 
.PP
.SS "typedef struct \fBANTLR3_REWRITE_RULE_ELEMENT_STREAM_struct\fP* \fBpANTLR3_REWRITE_RULE_SUBTREE_STREAM\fP"
.PP
Pointer to an instantiation of 'class' ANTLR3_REWRITE_RULE_SUBSTREE_STREAM. 
.PP
.SS "typedef struct \fBANTLR3_TOPO_struct\fP* \fBpANTLR3_TOPO\fP"
.PP
Pointer to an instantiation of 'class' \fBANTLR3_TOPO\fP. 
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for ANTLR3C from the source code.
