.TH "PANTLR3_INT_STREAM" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PANTLR3_INT_STREAM \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "ANTLR3_API \fBpANTLR3_INT_STREAM\fP \fBantlr3IntStreamNew\fP ()"
.br
.ti -1c
.RI "static void \fBfreeStream\fP (\fBpANTLR3_INT_STREAM\fP stream)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ANTLR3_API \fBpANTLR3_INT_STREAM\fP antlr3IntStreamNew (void)"
.PP
References ANTLR3_CALLOC, ANTLR3_INT_STREAM_struct::free, and freeStream().
.PP
Referenced by antlr3CommonTokenStreamNew(), antlr3CommonTreeNodeStreamNew(), antlr3CommonTreeNodeStreamNewStream(), and antlr3GenericSetupStream().
.SS "static void freeStream (\fBpANTLR3_INT_STREAM\fP stream)\fC [static]\fP"
.PP
References ANTLR3_FREE.
.PP
Referenced by antlr3IntStreamNew().
