.TH "pANTLR3_COMMON_TREE_ADAPTOR - Common Tree Adaptor Implementation" 3 "29 Nov 2010" "Version 3.3" "ANTLR3C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pANTLR3_COMMON_TREE_ADAPTOR - Common Tree Adaptor Implementation \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBantlr3commontreeadaptor.c\fP"
.br
.RI "\fIThis is the standard tree adaptor used by the C runtime unless the grammar source file says to use anything different. \fP"
.PP

.in -1c
